<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <OutputType>Library</OutputType>
        <Title>AEMET sample module</Title>
        <Description>Example module for Horizonte.Net, which provides access to the AEMET meteorological service. Service key is required</Description>
        <IsPackable>true</IsPackable>
    </PropertyGroup>


    <ItemGroup Condition="'$(UseProjectReferences)' == 'true'">
      <ProjectReference Include="..\Horizonte\Horizonte.csproj" />
        <ProjectReference Include="..\AdminUi.Components\AdminUi.Components.csproj" />
    </ItemGroup>
    <ItemGroup Condition="'$(UseProjectReferences)' == 'false'">
        <PackageReference Include="Horizonte" Version="$(InternalPackageVersion)" />
        <PackageReference Include="AdminUi.Components" Version="$(InternalPackageVersion)" />
    </ItemGroup>
    <ItemGroup>
      <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
      <PackageReference Include="Polly" Version="8.6.5" />
      <PackageReference Include="RestSharp" Version="113.0.1-alpha.0.3" />
    </ItemGroup>

    <ItemGroup>
      <None Update="README.md">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
    </ItemGroup>
</Project>
