<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <FileVersion>1.0.0</FileVersion>
        <OutputType>Library</OutputType>
        <Title>AEMET sample module</Title>
        <Authors>franfusto@gmail.com</Authors>
        <Description>Example module for Horizonte.Net, which provides access to the AEMET meteorological service.
Service key is required</Description>
        <Copyright>MIT</Copyright>
        <PackageProjectUrl>https://github.com/franfusto/HorizonteNet</PackageProjectUrl>
        <AssemblyVersion>1.0.0</AssemblyVersion>
        <IsPackable>true</IsPackable>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
      <DebugType>embedded</DebugType>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\AdminUi.Components\AdminUi.Components.csproj" />
      <ProjectReference Include="..\Horizonte\Horizonte.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
      <PackageReference Include="Polly" Version="8.6.5" />
      <PackageReference Include="Radzen.Blazor" Version="8.4.2" />
      <PackageReference Include="RestSharp" Version="113.0.1-alpha.0.3" />
    </ItemGroup>

    <ItemGroup>
      <None Update="README.md">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
    </ItemGroup>
</Project>
