/*
 * AEMET OpenData
 *
 * AEMET OpenData es una API REST desarrollado por AEMET que permite la difusión y la reutilización de la información meteorológica y climatológica de la Agencia, en el sentido indicado en la Ley 18/2015, de 9 de julio, por la que se modifica la Ley 37/2007, de 16 de noviembre, sobre reutilización de la información del sector público. (IMPORTANTE: Para poder realizar peticiones, es necesario introducir en API Key haciendo clic en el círculo rojo de recurso REST).<br><br>`IMPORTANTE`: Para poder realizar peticiones, es necesario introducir el `api_key` y haciendo clic en el botón `'Authorize'`. Después pulse en el botón `'Try it out'´ del recurso que quiera consultar.
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Horizonte.Samples.Aemet.Client;
using Org.OpenAPITools.Client;
using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IIndicesIncendiosApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Mapa de niveles de riesgo estimado meteorológico de incendios forestales.
        /// </summary>
        /// <remarks>
        /// Último mapa elaborado de niveles de riesgo estimado meteorológico de incendios forestales para el área pasada por parámetro.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="area"> | Código | Área | |- -- -- -- -- -|- -- -- -- -- -| | p  | Península y Baleares  | | c  | Canarias   </param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>Model200</returns>
        Model200 MapaDeNivelesDeRiesgoEstimadoMeteorolgicoDeIncendiosForestales(string area, int operationIndex = 0);

        /// <summary>
        /// Mapa de niveles de riesgo estimado meteorológico de incendios forestales.
        /// </summary>
        /// <remarks>
        /// Último mapa elaborado de niveles de riesgo estimado meteorológico de incendios forestales para el área pasada por parámetro.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="area"> | Código | Área | |- -- -- -- -- -|- -- -- -- -- -| | p  | Península y Baleares  | | c  | Canarias   </param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Model200</returns>
        ApiResponse<Model200> MapaDeNivelesDeRiesgoEstimadoMeteorolgicoDeIncendiosForestalesWithHttpInfo(string area, int operationIndex = 0);
        /// <summary>
        /// Mapa de niveles de riesgo previsto meteorológico de incendios forestales.
        /// </summary>
        /// <remarks>
        /// Mapa elaborado de niveles de riesgo estimado meteorológico de incendios forestales para el día y el área pasados por parámetro.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="dia"> | Código | Día | |- -- -- -- -- -|- -- -- -- -- -| | 1  | Mañana   | | 2  | Pasado Mañana   | | 3  | Dentro de 3 días   | | 4  | Dentro de 4 días   | | 5  | Dentro de 5 días   | | 6  | Dentro de 6 días   | | 7  | Dentro de 7 días   </param>
        /// <param name="area"> | Código | Área | |- -- -- -- -- -|- -- -- -- -- -| | p  | Península y Baleares  | | c  | Canarias   </param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>Model200</returns>
        Model200 MapaDeNivelesDeRiesgoPrevistoMeteorolgicoDeIncendiosForestales(string dia, string area, int operationIndex = 0);

        /// <summary>
        /// Mapa de niveles de riesgo previsto meteorológico de incendios forestales.
        /// </summary>
        /// <remarks>
        /// Mapa elaborado de niveles de riesgo estimado meteorológico de incendios forestales para el día y el área pasados por parámetro.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="dia"> | Código | Día | |- -- -- -- -- -|- -- -- -- -- -| | 1  | Mañana   | | 2  | Pasado Mañana   | | 3  | Dentro de 3 días   | | 4  | Dentro de 4 días   | | 5  | Dentro de 5 días   | | 6  | Dentro de 6 días   | | 7  | Dentro de 7 días   </param>
        /// <param name="area"> | Código | Área | |- -- -- -- -- -|- -- -- -- -- -| | p  | Península y Baleares  | | c  | Canarias   </param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Model200</returns>
        ApiResponse<Model200> MapaDeNivelesDeRiesgoPrevistoMeteorolgicoDeIncendiosForestalesWithHttpInfo(string dia, string area, int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IIndicesIncendiosApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Mapa de niveles de riesgo estimado meteorológico de incendios forestales.
        /// </summary>
        /// <remarks>
        /// Último mapa elaborado de niveles de riesgo estimado meteorológico de incendios forestales para el área pasada por parámetro.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="area"> | Código | Área | |- -- -- -- -- -|- -- -- -- -- -| | p  | Península y Baleares  | | c  | Canarias   </param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Model200</returns>
        System.Threading.Tasks.Task<Model200> MapaDeNivelesDeRiesgoEstimadoMeteorolgicoDeIncendiosForestalesAsync(string area, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Mapa de niveles de riesgo estimado meteorológico de incendios forestales.
        /// </summary>
        /// <remarks>
        /// Último mapa elaborado de niveles de riesgo estimado meteorológico de incendios forestales para el área pasada por parámetro.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="area"> | Código | Área | |- -- -- -- -- -|- -- -- -- -- -| | p  | Península y Baleares  | | c  | Canarias   </param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Model200)</returns>
        System.Threading.Tasks.Task<ApiResponse<Model200>> MapaDeNivelesDeRiesgoEstimadoMeteorolgicoDeIncendiosForestalesWithHttpInfoAsync(string area, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Mapa de niveles de riesgo previsto meteorológico de incendios forestales.
        /// </summary>
        /// <remarks>
        /// Mapa elaborado de niveles de riesgo estimado meteorológico de incendios forestales para el día y el área pasados por parámetro.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="dia"> | Código | Día | |- -- -- -- -- -|- -- -- -- -- -| | 1  | Mañana   | | 2  | Pasado Mañana   | | 3  | Dentro de 3 días   | | 4  | Dentro de 4 días   | | 5  | Dentro de 5 días   | | 6  | Dentro de 6 días   | | 7  | Dentro de 7 días   </param>
        /// <param name="area"> | Código | Área | |- -- -- -- -- -|- -- -- -- -- -| | p  | Península y Baleares  | | c  | Canarias   </param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Model200</returns>
        System.Threading.Tasks.Task<Model200> MapaDeNivelesDeRiesgoPrevistoMeteorolgicoDeIncendiosForestalesAsync(string dia, string area, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Mapa de niveles de riesgo previsto meteorológico de incendios forestales.
        /// </summary>
        /// <remarks>
        /// Mapa elaborado de niveles de riesgo estimado meteorológico de incendios forestales para el día y el área pasados por parámetro.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="dia"> | Código | Día | |- -- -- -- -- -|- -- -- -- -- -| | 1  | Mañana   | | 2  | Pasado Mañana   | | 3  | Dentro de 3 días   | | 4  | Dentro de 4 días   | | 5  | Dentro de 5 días   | | 6  | Dentro de 6 días   | | 7  | Dentro de 7 días   </param>
        /// <param name="area"> | Código | Área | |- -- -- -- -- -|- -- -- -- -- -| | p  | Península y Baleares  | | c  | Canarias   </param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Model200)</returns>
        System.Threading.Tasks.Task<ApiResponse<Model200>> MapaDeNivelesDeRiesgoPrevistoMeteorolgicoDeIncendiosForestalesWithHttpInfoAsync(string dia, string area, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IIndicesIncendiosApi : IIndicesIncendiosApiSync, IIndicesIncendiosApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class IndicesIncendiosApi : IIndicesIncendiosApi
    {
        private Org.OpenAPITools.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="IndicesIncendiosApi"/> class.
        /// </summary>
        /// <returns></returns>
        public IndicesIncendiosApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="IndicesIncendiosApi"/> class.
        /// </summary>
        /// <returns></returns>
        public IndicesIncendiosApi(string basePath)
        {
            this.Configuration = Org.OpenAPITools.Client.Configuration.MergeConfigurations(
                Org.OpenAPITools.Client.GlobalConfiguration.Instance,
                new Org.OpenAPITools.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="IndicesIncendiosApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public IndicesIncendiosApi(Org.OpenAPITools.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Org.OpenAPITools.Client.Configuration.MergeConfigurations(
                Org.OpenAPITools.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="IndicesIncendiosApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public IndicesIncendiosApi(Org.OpenAPITools.Client.ISynchronousClient client, Org.OpenAPITools.Client.IAsynchronousClient asyncClient, Org.OpenAPITools.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Org.OpenAPITools.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Org.OpenAPITools.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Org.OpenAPITools.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Org.OpenAPITools.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Mapa de niveles de riesgo estimado meteorológico de incendios forestales. Último mapa elaborado de niveles de riesgo estimado meteorológico de incendios forestales para el área pasada por parámetro.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="area"> | Código | Área | |- -- -- -- -- -|- -- -- -- -- -| | p  | Península y Baleares  | | c  | Canarias   </param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>Model200</returns>
        public Model200 MapaDeNivelesDeRiesgoEstimadoMeteorolgicoDeIncendiosForestales(string area, int operationIndex = 0)
        {
            Org.OpenAPITools.Client.ApiResponse<Model200> localVarResponse = MapaDeNivelesDeRiesgoEstimadoMeteorolgicoDeIncendiosForestalesWithHttpInfo(area);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Mapa de niveles de riesgo estimado meteorológico de incendios forestales. Último mapa elaborado de niveles de riesgo estimado meteorológico de incendios forestales para el área pasada por parámetro.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="area"> | Código | Área | |- -- -- -- -- -|- -- -- -- -- -| | p  | Península y Baleares  | | c  | Canarias   </param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Model200</returns>
        public Org.OpenAPITools.Client.ApiResponse<Model200> MapaDeNivelesDeRiesgoEstimadoMeteorolgicoDeIncendiosForestalesWithHttpInfo(string area, int operationIndex = 0)
        {
            // verify the required parameter 'area' is set
            if (area == null)
            {
                throw new ApiException(400, "Missing required parameter 'area' when calling IndicesIncendiosApi->MapaDeNivelesDeRiesgoEstimadoMeteorolgicoDeIncendiosForestales");
            }

            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("area", Org.OpenAPITools.Client.ClientUtils.ParameterToString(area)); // path parameter

            localVarRequestOptions.Operation = "IndicesIncendiosApi.MapaDeNivelesDeRiesgoEstimadoMeteorolgicoDeIncendiosForestales";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (api_key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("api_key")))
            {
                localVarRequestOptions.HeaderParameters.Add("api_key", this.Configuration.GetApiKeyWithPrefix("api_key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<Model200>("/api/incendios/mapasriesgo/estimado/area/{area}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("MapaDeNivelesDeRiesgoEstimadoMeteorolgicoDeIncendiosForestales", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Mapa de niveles de riesgo estimado meteorológico de incendios forestales. Último mapa elaborado de niveles de riesgo estimado meteorológico de incendios forestales para el área pasada por parámetro.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="area"> | Código | Área | |- -- -- -- -- -|- -- -- -- -- -| | p  | Península y Baleares  | | c  | Canarias   </param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Model200</returns>
        public async System.Threading.Tasks.Task<Model200> MapaDeNivelesDeRiesgoEstimadoMeteorolgicoDeIncendiosForestalesAsync(string area, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Org.OpenAPITools.Client.ApiResponse<Model200> localVarResponse = await MapaDeNivelesDeRiesgoEstimadoMeteorolgicoDeIncendiosForestalesWithHttpInfoAsync(area, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Mapa de niveles de riesgo estimado meteorológico de incendios forestales. Último mapa elaborado de niveles de riesgo estimado meteorológico de incendios forestales para el área pasada por parámetro.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="area"> | Código | Área | |- -- -- -- -- -|- -- -- -- -- -| | p  | Península y Baleares  | | c  | Canarias   </param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Model200)</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<Model200>> MapaDeNivelesDeRiesgoEstimadoMeteorolgicoDeIncendiosForestalesWithHttpInfoAsync(string area, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'area' is set
            if (area == null)
            {
                throw new ApiException(400, "Missing required parameter 'area' when calling IndicesIncendiosApi->MapaDeNivelesDeRiesgoEstimadoMeteorolgicoDeIncendiosForestales");
            }


            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("area", Org.OpenAPITools.Client.ClientUtils.ParameterToString(area)); // path parameter

            localVarRequestOptions.Operation = "IndicesIncendiosApi.MapaDeNivelesDeRiesgoEstimadoMeteorolgicoDeIncendiosForestales";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (api_key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("api_key")))
            {
                localVarRequestOptions.HeaderParameters.Add("api_key", this.Configuration.GetApiKeyWithPrefix("api_key"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<Model200>("/api/incendios/mapasriesgo/estimado/area/{area}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("MapaDeNivelesDeRiesgoEstimadoMeteorolgicoDeIncendiosForestales", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Mapa de niveles de riesgo previsto meteorológico de incendios forestales. Mapa elaborado de niveles de riesgo estimado meteorológico de incendios forestales para el día y el área pasados por parámetro.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="dia"> | Código | Día | |- -- -- -- -- -|- -- -- -- -- -| | 1  | Mañana   | | 2  | Pasado Mañana   | | 3  | Dentro de 3 días   | | 4  | Dentro de 4 días   | | 5  | Dentro de 5 días   | | 6  | Dentro de 6 días   | | 7  | Dentro de 7 días   </param>
        /// <param name="area"> | Código | Área | |- -- -- -- -- -|- -- -- -- -- -| | p  | Península y Baleares  | | c  | Canarias   </param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>Model200</returns>
        public Model200 MapaDeNivelesDeRiesgoPrevistoMeteorolgicoDeIncendiosForestales(string dia, string area, int operationIndex = 0)
        {
            Org.OpenAPITools.Client.ApiResponse<Model200> localVarResponse = MapaDeNivelesDeRiesgoPrevistoMeteorolgicoDeIncendiosForestalesWithHttpInfo(dia, area);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Mapa de niveles de riesgo previsto meteorológico de incendios forestales. Mapa elaborado de niveles de riesgo estimado meteorológico de incendios forestales para el día y el área pasados por parámetro.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="dia"> | Código | Día | |- -- -- -- -- -|- -- -- -- -- -| | 1  | Mañana   | | 2  | Pasado Mañana   | | 3  | Dentro de 3 días   | | 4  | Dentro de 4 días   | | 5  | Dentro de 5 días   | | 6  | Dentro de 6 días   | | 7  | Dentro de 7 días   </param>
        /// <param name="area"> | Código | Área | |- -- -- -- -- -|- -- -- -- -- -| | p  | Península y Baleares  | | c  | Canarias   </param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Model200</returns>
        public Org.OpenAPITools.Client.ApiResponse<Model200> MapaDeNivelesDeRiesgoPrevistoMeteorolgicoDeIncendiosForestalesWithHttpInfo(string dia, string area, int operationIndex = 0)
        {
            // verify the required parameter 'dia' is set
            if (dia == null)
            {
                throw new ApiException(400, "Missing required parameter 'dia' when calling IndicesIncendiosApi->MapaDeNivelesDeRiesgoPrevistoMeteorolgicoDeIncendiosForestales");
            }

            // verify the required parameter 'area' is set
            if (area == null)
            {
                throw new ApiException(400, "Missing required parameter 'area' when calling IndicesIncendiosApi->MapaDeNivelesDeRiesgoPrevistoMeteorolgicoDeIncendiosForestales");
            }

            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("dia", Org.OpenAPITools.Client.ClientUtils.ParameterToString(dia)); // path parameter
            localVarRequestOptions.PathParameters.Add("area", Org.OpenAPITools.Client.ClientUtils.ParameterToString(area)); // path parameter

            localVarRequestOptions.Operation = "IndicesIncendiosApi.MapaDeNivelesDeRiesgoPrevistoMeteorolgicoDeIncendiosForestales";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (api_key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("api_key")))
            {
                localVarRequestOptions.HeaderParameters.Add("api_key", this.Configuration.GetApiKeyWithPrefix("api_key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<Model200>("/api/incendios/mapasriesgo/previsto/dia/{dia}/area/{area}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("MapaDeNivelesDeRiesgoPrevistoMeteorolgicoDeIncendiosForestales", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Mapa de niveles de riesgo previsto meteorológico de incendios forestales. Mapa elaborado de niveles de riesgo estimado meteorológico de incendios forestales para el día y el área pasados por parámetro.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="dia"> | Código | Día | |- -- -- -- -- -|- -- -- -- -- -| | 1  | Mañana   | | 2  | Pasado Mañana   | | 3  | Dentro de 3 días   | | 4  | Dentro de 4 días   | | 5  | Dentro de 5 días   | | 6  | Dentro de 6 días   | | 7  | Dentro de 7 días   </param>
        /// <param name="area"> | Código | Área | |- -- -- -- -- -|- -- -- -- -- -| | p  | Península y Baleares  | | c  | Canarias   </param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Model200</returns>
        public async System.Threading.Tasks.Task<Model200> MapaDeNivelesDeRiesgoPrevistoMeteorolgicoDeIncendiosForestalesAsync(string dia, string area, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Org.OpenAPITools.Client.ApiResponse<Model200> localVarResponse = await MapaDeNivelesDeRiesgoPrevistoMeteorolgicoDeIncendiosForestalesWithHttpInfoAsync(dia, area, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Mapa de niveles de riesgo previsto meteorológico de incendios forestales. Mapa elaborado de niveles de riesgo estimado meteorológico de incendios forestales para el día y el área pasados por parámetro.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="dia"> | Código | Día | |- -- -- -- -- -|- -- -- -- -- -| | 1  | Mañana   | | 2  | Pasado Mañana   | | 3  | Dentro de 3 días   | | 4  | Dentro de 4 días   | | 5  | Dentro de 5 días   | | 6  | Dentro de 6 días   | | 7  | Dentro de 7 días   </param>
        /// <param name="area"> | Código | Área | |- -- -- -- -- -|- -- -- -- -- -| | p  | Península y Baleares  | | c  | Canarias   </param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Model200)</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<Model200>> MapaDeNivelesDeRiesgoPrevistoMeteorolgicoDeIncendiosForestalesWithHttpInfoAsync(string dia, string area, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'dia' is set
            if (dia == null)
            {
                throw new ApiException(400, "Missing required parameter 'dia' when calling IndicesIncendiosApi->MapaDeNivelesDeRiesgoPrevistoMeteorolgicoDeIncendiosForestales");
            }

            // verify the required parameter 'area' is set
            if (area == null)
            {
                throw new ApiException(400, "Missing required parameter 'area' when calling IndicesIncendiosApi->MapaDeNivelesDeRiesgoPrevistoMeteorolgicoDeIncendiosForestales");
            }


            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("dia", Org.OpenAPITools.Client.ClientUtils.ParameterToString(dia)); // path parameter
            localVarRequestOptions.PathParameters.Add("area", Org.OpenAPITools.Client.ClientUtils.ParameterToString(area)); // path parameter

            localVarRequestOptions.Operation = "IndicesIncendiosApi.MapaDeNivelesDeRiesgoPrevistoMeteorolgicoDeIncendiosForestales";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (api_key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("api_key")))
            {
                localVarRequestOptions.HeaderParameters.Add("api_key", this.Configuration.GetApiKeyWithPrefix("api_key"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<Model200>("/api/incendios/mapasriesgo/previsto/dia/{dia}/area/{area}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("MapaDeNivelesDeRiesgoPrevistoMeteorolgicoDeIncendiosForestales", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
