/*
 * AEMET OpenData
 *
 * AEMET OpenData es una API REST desarrollado por AEMET que permite la difusión y la reutilización de la información meteorológica y climatológica de la Agencia, en el sentido indicado en la Ley 18/2015, de 9 de julio, por la que se modifica la Ley 37/2007, de 16 de noviembre, sobre reutilización de la información del sector público. (IMPORTANTE: Para poder realizar peticiones, es necesario introducir en API Key haciendo clic en el círculo rojo de recurso REST).<br><br>`IMPORTANTE`: Para poder realizar peticiones, es necesario introducir el `api_key` y haciendo clic en el botón `'Authorize'`. Después pulse en el botón `'Try it out'´ del recurso que quiera consultar.
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Org.OpenAPITools.Client;
using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IObservacionConvencionalApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Datos de observación. Tiempo actual.
        /// </summary>
        /// <remarks>
        /// Datos de observación horarios de las últimas 12 horas todas las estaciones meteorológicas de las que se han recibido datos en ese período. Frecuencia de actualización: continuamente. &lt;br&gt;&lt;br&gt; &lt;a href&#x3D;&#39;https://opendata.aemet.es/centrodedescargas/rssatom&#39;     target&#x3D;&#39;_blank&#39;&gt;Canales RSS&lt;/a&gt; disponibles:         &lt;ul&gt;         &lt;li&gt;Observación convencional horaria&lt;/li&gt;         &lt;/ul&gt;
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>Model200</returns>
        Model200 DatosDeObservacinTiempoActual(int operationIndex = 0);

        /// <summary>
        /// Datos de observación. Tiempo actual.
        /// </summary>
        /// <remarks>
        /// Datos de observación horarios de las últimas 12 horas todas las estaciones meteorológicas de las que se han recibido datos en ese período. Frecuencia de actualización: continuamente. &lt;br&gt;&lt;br&gt; &lt;a href&#x3D;&#39;https://opendata.aemet.es/centrodedescargas/rssatom&#39;     target&#x3D;&#39;_blank&#39;&gt;Canales RSS&lt;/a&gt; disponibles:         &lt;ul&gt;         &lt;li&gt;Observación convencional horaria&lt;/li&gt;         &lt;/ul&gt;
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Model200</returns>
        ApiResponse<Model200> DatosDeObservacinTiempoActualWithHttpInfo(int operationIndex = 0);
        /// <summary>
        /// Datos de observación. Tiempo actual.
        /// </summary>
        /// <remarks>
        /// Datos de observación horarios de las últimas 12 horas de la estación meterológica que se pasa como parámetro (idema). Frecuencia de actualización: continuamente. &lt;br&gt;&lt;br&gt; &lt;a href&#x3D;&#39;https://opendata.aemet.es/centrodedescargas/rssatom&#39;     target&#x3D;&#39;_blank&#39;&gt;Canales RSS&lt;/a&gt; disponibles:         &lt;ul&gt;         &lt;li&gt;Observación convencional horaria&lt;/li&gt;         &lt;/ul&gt;
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="idema">Índicativo climatológico de la EMA</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>Model200</returns>
        Model200 DatosDeObservacinTiempoActual1(string idema, int operationIndex = 0);

        /// <summary>
        /// Datos de observación. Tiempo actual.
        /// </summary>
        /// <remarks>
        /// Datos de observación horarios de las últimas 12 horas de la estación meterológica que se pasa como parámetro (idema). Frecuencia de actualización: continuamente. &lt;br&gt;&lt;br&gt; &lt;a href&#x3D;&#39;https://opendata.aemet.es/centrodedescargas/rssatom&#39;     target&#x3D;&#39;_blank&#39;&gt;Canales RSS&lt;/a&gt; disponibles:         &lt;ul&gt;         &lt;li&gt;Observación convencional horaria&lt;/li&gt;         &lt;/ul&gt;
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="idema">Índicativo climatológico de la EMA</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Model200</returns>
        ApiResponse<Model200> DatosDeObservacinTiempoActual1WithHttpInfo(string idema, int operationIndex = 0);
        /// <summary>
        /// Mensajes de observación. Último elaborado.
        /// </summary>
        /// <remarks>
        /// Últimos mensajes de observación. Para los SYNOP y TEMP devuelve los mensajes de las últimas 24 horas y para los CLIMAT de los 40 últimos dias. Se pasa como parámetro el tipo de mensaje que se desea (tipomensaje). El resultado de la petición es un fichero en formato tar.gz, que contiene los boletines en formato json y bufr.&lt;br&gt;&lt;br&gt; &lt;a href&#x3D;&#39;https://opendata.aemet.es/centrodedescargas/rssatom&#39;     target&#x3D;&#39;_blank&#39;&gt;Canales RSS&lt;/a&gt; disponibles:         &lt;ul&gt;         &lt;li&gt;Observación convencional mensajes: climat&lt;/li&gt;         &lt;li&gt;Observación convencional mensajes: synop&lt;/li&gt;         &lt;li&gt;Observación convencional mensajes: temp&lt;/li&gt;         &lt;li&gt;Observación convencional mensajes: todos&lt;/li&gt;         &lt;/ul&gt;
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tipomensaje"> | Código | Tipo de Mensaje | |- -- -- -- -- -|- -- -- -- -- -| | climat  | climat   | | synop  | synop   | | temp  | temp  </param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>Model200</returns>
        Model200 MensajesDeObservacinLtimoElaborado(string tipomensaje, int operationIndex = 0);

        /// <summary>
        /// Mensajes de observación. Último elaborado.
        /// </summary>
        /// <remarks>
        /// Últimos mensajes de observación. Para los SYNOP y TEMP devuelve los mensajes de las últimas 24 horas y para los CLIMAT de los 40 últimos dias. Se pasa como parámetro el tipo de mensaje que se desea (tipomensaje). El resultado de la petición es un fichero en formato tar.gz, que contiene los boletines en formato json y bufr.&lt;br&gt;&lt;br&gt; &lt;a href&#x3D;&#39;https://opendata.aemet.es/centrodedescargas/rssatom&#39;     target&#x3D;&#39;_blank&#39;&gt;Canales RSS&lt;/a&gt; disponibles:         &lt;ul&gt;         &lt;li&gt;Observación convencional mensajes: climat&lt;/li&gt;         &lt;li&gt;Observación convencional mensajes: synop&lt;/li&gt;         &lt;li&gt;Observación convencional mensajes: temp&lt;/li&gt;         &lt;li&gt;Observación convencional mensajes: todos&lt;/li&gt;         &lt;/ul&gt;
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tipomensaje"> | Código | Tipo de Mensaje | |- -- -- -- -- -|- -- -- -- -- -| | climat  | climat   | | synop  | synop   | | temp  | temp  </param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Model200</returns>
        ApiResponse<Model200> MensajesDeObservacinLtimoElaboradoWithHttpInfo(string tipomensaje, int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IObservacionConvencionalApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Datos de observación. Tiempo actual.
        /// </summary>
        /// <remarks>
        /// Datos de observación horarios de las últimas 12 horas todas las estaciones meteorológicas de las que se han recibido datos en ese período. Frecuencia de actualización: continuamente. &lt;br&gt;&lt;br&gt; &lt;a href&#x3D;&#39;https://opendata.aemet.es/centrodedescargas/rssatom&#39;     target&#x3D;&#39;_blank&#39;&gt;Canales RSS&lt;/a&gt; disponibles:         &lt;ul&gt;         &lt;li&gt;Observación convencional horaria&lt;/li&gt;         &lt;/ul&gt;
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Model200</returns>
        System.Threading.Tasks.Task<Model200> DatosDeObservacinTiempoActualAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Datos de observación. Tiempo actual.
        /// </summary>
        /// <remarks>
        /// Datos de observación horarios de las últimas 12 horas todas las estaciones meteorológicas de las que se han recibido datos en ese período. Frecuencia de actualización: continuamente. &lt;br&gt;&lt;br&gt; &lt;a href&#x3D;&#39;https://opendata.aemet.es/centrodedescargas/rssatom&#39;     target&#x3D;&#39;_blank&#39;&gt;Canales RSS&lt;/a&gt; disponibles:         &lt;ul&gt;         &lt;li&gt;Observación convencional horaria&lt;/li&gt;         &lt;/ul&gt;
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Model200)</returns>
        System.Threading.Tasks.Task<ApiResponse<Model200>> DatosDeObservacinTiempoActualWithHttpInfoAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Datos de observación. Tiempo actual.
        /// </summary>
        /// <remarks>
        /// Datos de observación horarios de las últimas 12 horas de la estación meterológica que se pasa como parámetro (idema). Frecuencia de actualización: continuamente. &lt;br&gt;&lt;br&gt; &lt;a href&#x3D;&#39;https://opendata.aemet.es/centrodedescargas/rssatom&#39;     target&#x3D;&#39;_blank&#39;&gt;Canales RSS&lt;/a&gt; disponibles:         &lt;ul&gt;         &lt;li&gt;Observación convencional horaria&lt;/li&gt;         &lt;/ul&gt;
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="idema">Índicativo climatológico de la EMA</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Model200</returns>
        System.Threading.Tasks.Task<Model200> DatosDeObservacinTiempoActual1Async(string idema, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Datos de observación. Tiempo actual.
        /// </summary>
        /// <remarks>
        /// Datos de observación horarios de las últimas 12 horas de la estación meterológica que se pasa como parámetro (idema). Frecuencia de actualización: continuamente. &lt;br&gt;&lt;br&gt; &lt;a href&#x3D;&#39;https://opendata.aemet.es/centrodedescargas/rssatom&#39;     target&#x3D;&#39;_blank&#39;&gt;Canales RSS&lt;/a&gt; disponibles:         &lt;ul&gt;         &lt;li&gt;Observación convencional horaria&lt;/li&gt;         &lt;/ul&gt;
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="idema">Índicativo climatológico de la EMA</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Model200)</returns>
        System.Threading.Tasks.Task<ApiResponse<Model200>> DatosDeObservacinTiempoActual1WithHttpInfoAsync(string idema, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Mensajes de observación. Último elaborado.
        /// </summary>
        /// <remarks>
        /// Últimos mensajes de observación. Para los SYNOP y TEMP devuelve los mensajes de las últimas 24 horas y para los CLIMAT de los 40 últimos dias. Se pasa como parámetro el tipo de mensaje que se desea (tipomensaje). El resultado de la petición es un fichero en formato tar.gz, que contiene los boletines en formato json y bufr.&lt;br&gt;&lt;br&gt; &lt;a href&#x3D;&#39;https://opendata.aemet.es/centrodedescargas/rssatom&#39;     target&#x3D;&#39;_blank&#39;&gt;Canales RSS&lt;/a&gt; disponibles:         &lt;ul&gt;         &lt;li&gt;Observación convencional mensajes: climat&lt;/li&gt;         &lt;li&gt;Observación convencional mensajes: synop&lt;/li&gt;         &lt;li&gt;Observación convencional mensajes: temp&lt;/li&gt;         &lt;li&gt;Observación convencional mensajes: todos&lt;/li&gt;         &lt;/ul&gt;
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tipomensaje"> | Código | Tipo de Mensaje | |- -- -- -- -- -|- -- -- -- -- -| | climat  | climat   | | synop  | synop   | | temp  | temp  </param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Model200</returns>
        System.Threading.Tasks.Task<Model200> MensajesDeObservacinLtimoElaboradoAsync(string tipomensaje, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Mensajes de observación. Último elaborado.
        /// </summary>
        /// <remarks>
        /// Últimos mensajes de observación. Para los SYNOP y TEMP devuelve los mensajes de las últimas 24 horas y para los CLIMAT de los 40 últimos dias. Se pasa como parámetro el tipo de mensaje que se desea (tipomensaje). El resultado de la petición es un fichero en formato tar.gz, que contiene los boletines en formato json y bufr.&lt;br&gt;&lt;br&gt; &lt;a href&#x3D;&#39;https://opendata.aemet.es/centrodedescargas/rssatom&#39;     target&#x3D;&#39;_blank&#39;&gt;Canales RSS&lt;/a&gt; disponibles:         &lt;ul&gt;         &lt;li&gt;Observación convencional mensajes: climat&lt;/li&gt;         &lt;li&gt;Observación convencional mensajes: synop&lt;/li&gt;         &lt;li&gt;Observación convencional mensajes: temp&lt;/li&gt;         &lt;li&gt;Observación convencional mensajes: todos&lt;/li&gt;         &lt;/ul&gt;
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tipomensaje"> | Código | Tipo de Mensaje | |- -- -- -- -- -|- -- -- -- -- -| | climat  | climat   | | synop  | synop   | | temp  | temp  </param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Model200)</returns>
        System.Threading.Tasks.Task<ApiResponse<Model200>> MensajesDeObservacinLtimoElaboradoWithHttpInfoAsync(string tipomensaje, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IObservacionConvencionalApi : IObservacionConvencionalApiSync, IObservacionConvencionalApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class ObservacionConvencionalApi : IObservacionConvencionalApi
    {
        private Org.OpenAPITools.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="ObservacionConvencionalApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ObservacionConvencionalApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ObservacionConvencionalApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ObservacionConvencionalApi(string basePath)
        {
            this.Configuration = Org.OpenAPITools.Client.Configuration.MergeConfigurations(
                Org.OpenAPITools.Client.GlobalConfiguration.Instance,
                new Org.OpenAPITools.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ObservacionConvencionalApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public ObservacionConvencionalApi(Org.OpenAPITools.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Org.OpenAPITools.Client.Configuration.MergeConfigurations(
                Org.OpenAPITools.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ObservacionConvencionalApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public ObservacionConvencionalApi(Org.OpenAPITools.Client.ISynchronousClient client, Org.OpenAPITools.Client.IAsynchronousClient asyncClient, Org.OpenAPITools.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Org.OpenAPITools.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Org.OpenAPITools.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Org.OpenAPITools.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Org.OpenAPITools.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Datos de observación. Tiempo actual. Datos de observación horarios de las últimas 12 horas todas las estaciones meteorológicas de las que se han recibido datos en ese período. Frecuencia de actualización: continuamente. &lt;br&gt;&lt;br&gt; &lt;a href&#x3D;&#39;https://opendata.aemet.es/centrodedescargas/rssatom&#39;     target&#x3D;&#39;_blank&#39;&gt;Canales RSS&lt;/a&gt; disponibles:         &lt;ul&gt;         &lt;li&gt;Observación convencional horaria&lt;/li&gt;         &lt;/ul&gt;
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>Model200</returns>
        public Model200 DatosDeObservacinTiempoActual(int operationIndex = 0)
        {
            Org.OpenAPITools.Client.ApiResponse<Model200> localVarResponse = DatosDeObservacinTiempoActualWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        /// Datos de observación. Tiempo actual. Datos de observación horarios de las últimas 12 horas todas las estaciones meteorológicas de las que se han recibido datos en ese período. Frecuencia de actualización: continuamente. &lt;br&gt;&lt;br&gt; &lt;a href&#x3D;&#39;https://opendata.aemet.es/centrodedescargas/rssatom&#39;     target&#x3D;&#39;_blank&#39;&gt;Canales RSS&lt;/a&gt; disponibles:         &lt;ul&gt;         &lt;li&gt;Observación convencional horaria&lt;/li&gt;         &lt;/ul&gt;
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Model200</returns>
        public Org.OpenAPITools.Client.ApiResponse<Model200> DatosDeObservacinTiempoActualWithHttpInfo(int operationIndex = 0)
        {
            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }


            localVarRequestOptions.Operation = "ObservacionConvencionalApi.DatosDeObservacinTiempoActual";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (api_key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("api_key")))
            {
                localVarRequestOptions.HeaderParameters.Add("api_key", this.Configuration.GetApiKeyWithPrefix("api_key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<Model200>("/api/observacion/convencional/todas", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DatosDeObservacinTiempoActual", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Datos de observación. Tiempo actual. Datos de observación horarios de las últimas 12 horas todas las estaciones meteorológicas de las que se han recibido datos en ese período. Frecuencia de actualización: continuamente. &lt;br&gt;&lt;br&gt; &lt;a href&#x3D;&#39;https://opendata.aemet.es/centrodedescargas/rssatom&#39;     target&#x3D;&#39;_blank&#39;&gt;Canales RSS&lt;/a&gt; disponibles:         &lt;ul&gt;         &lt;li&gt;Observación convencional horaria&lt;/li&gt;         &lt;/ul&gt;
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Model200</returns>
        public async System.Threading.Tasks.Task<Model200> DatosDeObservacinTiempoActualAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Org.OpenAPITools.Client.ApiResponse<Model200> localVarResponse = await DatosDeObservacinTiempoActualWithHttpInfoAsync(operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Datos de observación. Tiempo actual. Datos de observación horarios de las últimas 12 horas todas las estaciones meteorológicas de las que se han recibido datos en ese período. Frecuencia de actualización: continuamente. &lt;br&gt;&lt;br&gt; &lt;a href&#x3D;&#39;https://opendata.aemet.es/centrodedescargas/rssatom&#39;     target&#x3D;&#39;_blank&#39;&gt;Canales RSS&lt;/a&gt; disponibles:         &lt;ul&gt;         &lt;li&gt;Observación convencional horaria&lt;/li&gt;         &lt;/ul&gt;
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Model200)</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<Model200>> DatosDeObservacinTiempoActualWithHttpInfoAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }


            localVarRequestOptions.Operation = "ObservacionConvencionalApi.DatosDeObservacinTiempoActual";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (api_key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("api_key")))
            {
                localVarRequestOptions.HeaderParameters.Add("api_key", this.Configuration.GetApiKeyWithPrefix("api_key"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<Model200>("/api/observacion/convencional/todas", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DatosDeObservacinTiempoActual", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Datos de observación. Tiempo actual. Datos de observación horarios de las últimas 12 horas de la estación meterológica que se pasa como parámetro (idema). Frecuencia de actualización: continuamente. &lt;br&gt;&lt;br&gt; &lt;a href&#x3D;&#39;https://opendata.aemet.es/centrodedescargas/rssatom&#39;     target&#x3D;&#39;_blank&#39;&gt;Canales RSS&lt;/a&gt; disponibles:         &lt;ul&gt;         &lt;li&gt;Observación convencional horaria&lt;/li&gt;         &lt;/ul&gt;
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="idema">Índicativo climatológico de la EMA</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>Model200</returns>
        public Model200 DatosDeObservacinTiempoActual1(string idema, int operationIndex = 0)
        {
            Org.OpenAPITools.Client.ApiResponse<Model200> localVarResponse = DatosDeObservacinTiempoActual1WithHttpInfo(idema);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Datos de observación. Tiempo actual. Datos de observación horarios de las últimas 12 horas de la estación meterológica que se pasa como parámetro (idema). Frecuencia de actualización: continuamente. &lt;br&gt;&lt;br&gt; &lt;a href&#x3D;&#39;https://opendata.aemet.es/centrodedescargas/rssatom&#39;     target&#x3D;&#39;_blank&#39;&gt;Canales RSS&lt;/a&gt; disponibles:         &lt;ul&gt;         &lt;li&gt;Observación convencional horaria&lt;/li&gt;         &lt;/ul&gt;
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="idema">Índicativo climatológico de la EMA</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Model200</returns>
        public Org.OpenAPITools.Client.ApiResponse<Model200> DatosDeObservacinTiempoActual1WithHttpInfo(string idema, int operationIndex = 0)
        {
            // verify the required parameter 'idema' is set
            if (idema == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'idema' when calling ObservacionConvencionalApi->DatosDeObservacinTiempoActual1");
            }

            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("idema", Org.OpenAPITools.Client.ClientUtils.ParameterToString(idema)); // path parameter

            localVarRequestOptions.Operation = "ObservacionConvencionalApi.DatosDeObservacinTiempoActual1";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (api_key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("api_key")))
            {
                localVarRequestOptions.HeaderParameters.Add("api_key", this.Configuration.GetApiKeyWithPrefix("api_key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<Model200>("/api/observacion/convencional/datos/estacion/{idema}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DatosDeObservacinTiempoActual1", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Datos de observación. Tiempo actual. Datos de observación horarios de las últimas 12 horas de la estación meterológica que se pasa como parámetro (idema). Frecuencia de actualización: continuamente. &lt;br&gt;&lt;br&gt; &lt;a href&#x3D;&#39;https://opendata.aemet.es/centrodedescargas/rssatom&#39;     target&#x3D;&#39;_blank&#39;&gt;Canales RSS&lt;/a&gt; disponibles:         &lt;ul&gt;         &lt;li&gt;Observación convencional horaria&lt;/li&gt;         &lt;/ul&gt;
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="idema">Índicativo climatológico de la EMA</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Model200</returns>
        public async System.Threading.Tasks.Task<Model200> DatosDeObservacinTiempoActual1Async(string idema, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Org.OpenAPITools.Client.ApiResponse<Model200> localVarResponse = await DatosDeObservacinTiempoActual1WithHttpInfoAsync(idema, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Datos de observación. Tiempo actual. Datos de observación horarios de las últimas 12 horas de la estación meterológica que se pasa como parámetro (idema). Frecuencia de actualización: continuamente. &lt;br&gt;&lt;br&gt; &lt;a href&#x3D;&#39;https://opendata.aemet.es/centrodedescargas/rssatom&#39;     target&#x3D;&#39;_blank&#39;&gt;Canales RSS&lt;/a&gt; disponibles:         &lt;ul&gt;         &lt;li&gt;Observación convencional horaria&lt;/li&gt;         &lt;/ul&gt;
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="idema">Índicativo climatológico de la EMA</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Model200)</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<Model200>> DatosDeObservacinTiempoActual1WithHttpInfoAsync(string idema, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'idema' is set
            if (idema == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'idema' when calling ObservacionConvencionalApi->DatosDeObservacinTiempoActual1");
            }


            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("idema", Org.OpenAPITools.Client.ClientUtils.ParameterToString(idema)); // path parameter

            localVarRequestOptions.Operation = "ObservacionConvencionalApi.DatosDeObservacinTiempoActual1";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (api_key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("api_key")))
            {
                localVarRequestOptions.HeaderParameters.Add("api_key", this.Configuration.GetApiKeyWithPrefix("api_key"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<Model200>("/api/observacion/convencional/datos/estacion/{idema}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DatosDeObservacinTiempoActual1", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Mensajes de observación. Último elaborado. Últimos mensajes de observación. Para los SYNOP y TEMP devuelve los mensajes de las últimas 24 horas y para los CLIMAT de los 40 últimos dias. Se pasa como parámetro el tipo de mensaje que se desea (tipomensaje). El resultado de la petición es un fichero en formato tar.gz, que contiene los boletines en formato json y bufr.&lt;br&gt;&lt;br&gt; &lt;a href&#x3D;&#39;https://opendata.aemet.es/centrodedescargas/rssatom&#39;     target&#x3D;&#39;_blank&#39;&gt;Canales RSS&lt;/a&gt; disponibles:         &lt;ul&gt;         &lt;li&gt;Observación convencional mensajes: climat&lt;/li&gt;         &lt;li&gt;Observación convencional mensajes: synop&lt;/li&gt;         &lt;li&gt;Observación convencional mensajes: temp&lt;/li&gt;         &lt;li&gt;Observación convencional mensajes: todos&lt;/li&gt;         &lt;/ul&gt;
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tipomensaje"> | Código | Tipo de Mensaje | |- -- -- -- -- -|- -- -- -- -- -| | climat  | climat   | | synop  | synop   | | temp  | temp  </param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>Model200</returns>
        public Model200 MensajesDeObservacinLtimoElaborado(string tipomensaje, int operationIndex = 0)
        {
            Org.OpenAPITools.Client.ApiResponse<Model200> localVarResponse = MensajesDeObservacinLtimoElaboradoWithHttpInfo(tipomensaje);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Mensajes de observación. Último elaborado. Últimos mensajes de observación. Para los SYNOP y TEMP devuelve los mensajes de las últimas 24 horas y para los CLIMAT de los 40 últimos dias. Se pasa como parámetro el tipo de mensaje que se desea (tipomensaje). El resultado de la petición es un fichero en formato tar.gz, que contiene los boletines en formato json y bufr.&lt;br&gt;&lt;br&gt; &lt;a href&#x3D;&#39;https://opendata.aemet.es/centrodedescargas/rssatom&#39;     target&#x3D;&#39;_blank&#39;&gt;Canales RSS&lt;/a&gt; disponibles:         &lt;ul&gt;         &lt;li&gt;Observación convencional mensajes: climat&lt;/li&gt;         &lt;li&gt;Observación convencional mensajes: synop&lt;/li&gt;         &lt;li&gt;Observación convencional mensajes: temp&lt;/li&gt;         &lt;li&gt;Observación convencional mensajes: todos&lt;/li&gt;         &lt;/ul&gt;
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tipomensaje"> | Código | Tipo de Mensaje | |- -- -- -- -- -|- -- -- -- -- -| | climat  | climat   | | synop  | synop   | | temp  | temp  </param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Model200</returns>
        public Org.OpenAPITools.Client.ApiResponse<Model200> MensajesDeObservacinLtimoElaboradoWithHttpInfo(string tipomensaje, int operationIndex = 0)
        {
            // verify the required parameter 'tipomensaje' is set
            if (tipomensaje == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'tipomensaje' when calling ObservacionConvencionalApi->MensajesDeObservacinLtimoElaborado");
            }

            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("tipomensaje", Org.OpenAPITools.Client.ClientUtils.ParameterToString(tipomensaje)); // path parameter

            localVarRequestOptions.Operation = "ObservacionConvencionalApi.MensajesDeObservacinLtimoElaborado";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (api_key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("api_key")))
            {
                localVarRequestOptions.HeaderParameters.Add("api_key", this.Configuration.GetApiKeyWithPrefix("api_key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<Model200>("/api/observacion/convencional/mensajes/tipomensaje/{tipomensaje}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("MensajesDeObservacinLtimoElaborado", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Mensajes de observación. Último elaborado. Últimos mensajes de observación. Para los SYNOP y TEMP devuelve los mensajes de las últimas 24 horas y para los CLIMAT de los 40 últimos dias. Se pasa como parámetro el tipo de mensaje que se desea (tipomensaje). El resultado de la petición es un fichero en formato tar.gz, que contiene los boletines en formato json y bufr.&lt;br&gt;&lt;br&gt; &lt;a href&#x3D;&#39;https://opendata.aemet.es/centrodedescargas/rssatom&#39;     target&#x3D;&#39;_blank&#39;&gt;Canales RSS&lt;/a&gt; disponibles:         &lt;ul&gt;         &lt;li&gt;Observación convencional mensajes: climat&lt;/li&gt;         &lt;li&gt;Observación convencional mensajes: synop&lt;/li&gt;         &lt;li&gt;Observación convencional mensajes: temp&lt;/li&gt;         &lt;li&gt;Observación convencional mensajes: todos&lt;/li&gt;         &lt;/ul&gt;
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tipomensaje"> | Código | Tipo de Mensaje | |- -- -- -- -- -|- -- -- -- -- -| | climat  | climat   | | synop  | synop   | | temp  | temp  </param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Model200</returns>
        public async System.Threading.Tasks.Task<Model200> MensajesDeObservacinLtimoElaboradoAsync(string tipomensaje, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Org.OpenAPITools.Client.ApiResponse<Model200> localVarResponse = await MensajesDeObservacinLtimoElaboradoWithHttpInfoAsync(tipomensaje, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Mensajes de observación. Último elaborado. Últimos mensajes de observación. Para los SYNOP y TEMP devuelve los mensajes de las últimas 24 horas y para los CLIMAT de los 40 últimos dias. Se pasa como parámetro el tipo de mensaje que se desea (tipomensaje). El resultado de la petición es un fichero en formato tar.gz, que contiene los boletines en formato json y bufr.&lt;br&gt;&lt;br&gt; &lt;a href&#x3D;&#39;https://opendata.aemet.es/centrodedescargas/rssatom&#39;     target&#x3D;&#39;_blank&#39;&gt;Canales RSS&lt;/a&gt; disponibles:         &lt;ul&gt;         &lt;li&gt;Observación convencional mensajes: climat&lt;/li&gt;         &lt;li&gt;Observación convencional mensajes: synop&lt;/li&gt;         &lt;li&gt;Observación convencional mensajes: temp&lt;/li&gt;         &lt;li&gt;Observación convencional mensajes: todos&lt;/li&gt;         &lt;/ul&gt;
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tipomensaje"> | Código | Tipo de Mensaje | |- -- -- -- -- -|- -- -- -- -- -| | climat  | climat   | | synop  | synop   | | temp  | temp  </param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Model200)</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<Model200>> MensajesDeObservacinLtimoElaboradoWithHttpInfoAsync(string tipomensaje, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'tipomensaje' is set
            if (tipomensaje == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'tipomensaje' when calling ObservacionConvencionalApi->MensajesDeObservacinLtimoElaborado");
            }


            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("tipomensaje", Org.OpenAPITools.Client.ClientUtils.ParameterToString(tipomensaje)); // path parameter

            localVarRequestOptions.Operation = "ObservacionConvencionalApi.MensajesDeObservacinLtimoElaborado";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (api_key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("api_key")))
            {
                localVarRequestOptions.HeaderParameters.Add("api_key", this.Configuration.GetApiKeyWithPrefix("api_key"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<Model200>("/api/observacion/convencional/mensajes/tipomensaje/{tipomensaje}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("MensajesDeObservacinLtimoElaborado", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
