/*
 * AEMET OpenData
 *
 * AEMET OpenData es una API REST desarrollado por AEMET que permite la difusión y la reutilización de la información meteorológica y climatológica de la Agencia, en el sentido indicado en la Ley 18/2015, de 9 de julio, por la que se modifica la Ley 37/2007, de 16 de noviembre, sobre reutilización de la información del sector público. (IMPORTANTE: Para poder realizar peticiones, es necesario introducir en API Key haciendo clic en el círculo rojo de recurso REST).<br><br>`IMPORTANTE`: Para poder realizar peticiones, es necesario introducir el `api_key` y haciendo clic en el botón `'Authorize'`. Después pulse en el botón `'Try it out'´ del recurso que quiera consultar.
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Horizonte.Samples.Aemet.Client;
using Org.OpenAPITools.Client;
using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IValoresClimatologicosApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Climatologías diarias.
        /// </summary>
        /// <remarks>
        /// Valores climatológicos para el rango de fechas y la estación seleccionada. Periodicidad: 1 vez al día.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="fechaIniStr">Fecha Inicial (AAAA-MM-DDTHH:MM:SSUTC)</param>
        /// <param name="fechaFinStr">Fecha Final (AAAA-MM-DDTHH:MM:SSUTC)</param>
        /// <param name="idema">Indicativo climatológico de la EMA. Puede introducir varios indicativos separados por comas (,)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>Model200</returns>
        Model200 ClimatologasDiarias(string fechaIniStr, string fechaFinStr, string idema, int operationIndex = 0);

        /// <summary>
        /// Climatologías diarias.
        /// </summary>
        /// <remarks>
        /// Valores climatológicos para el rango de fechas y la estación seleccionada. Periodicidad: 1 vez al día.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="fechaIniStr">Fecha Inicial (AAAA-MM-DDTHH:MM:SSUTC)</param>
        /// <param name="fechaFinStr">Fecha Final (AAAA-MM-DDTHH:MM:SSUTC)</param>
        /// <param name="idema">Indicativo climatológico de la EMA. Puede introducir varios indicativos separados por comas (,)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Model200</returns>
        ApiResponse<Model200> ClimatologasDiariasWithHttpInfo(string fechaIniStr, string fechaFinStr, string idema, int operationIndex = 0);
        /// <summary>
        /// Climatologías diarias.
        /// </summary>
        /// <remarks>
        /// Valores climatológicos de todas las estaciones para el rango de fechas seleccionado. Periodicidad: 1 vez al día.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="fechaIniStr">Fecha Inicial (AAAA-MM-DDTHH:MM:SSUTC)</param>
        /// <param name="fechaFinStr">Fecha Final (AAAA-MM-DDTHH:MM:SSUTC)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>Model200</returns>
        Model200 ClimatologasDiarias1(string fechaIniStr, string fechaFinStr, int operationIndex = 0);

        /// <summary>
        /// Climatologías diarias.
        /// </summary>
        /// <remarks>
        /// Valores climatológicos de todas las estaciones para el rango de fechas seleccionado. Periodicidad: 1 vez al día.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="fechaIniStr">Fecha Inicial (AAAA-MM-DDTHH:MM:SSUTC)</param>
        /// <param name="fechaFinStr">Fecha Final (AAAA-MM-DDTHH:MM:SSUTC)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Model200</returns>
        ApiResponse<Model200> ClimatologasDiarias1WithHttpInfo(string fechaIniStr, string fechaFinStr, int operationIndex = 0);
        /// <summary>
        /// Climatologías mensuales anuales.
        /// </summary>
        /// <remarks>
        /// Valores medios mensuales y anuales de los datos climatológicos para la estación y el periodo de años pasados por parámetro. Periodicidad de actualización: 1 vez al día.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="anioIniStr">Año Inicial (AAAA)</param>
        /// <param name="anioFinStr">Año Final (AAAA)</param>
        /// <param name="idema">Indicativo climatológico de la EMA</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>Model200</returns>
        Model200 ClimatologasMensualesAnuales(string anioIniStr, string anioFinStr, string idema, int operationIndex = 0);

        /// <summary>
        /// Climatologías mensuales anuales.
        /// </summary>
        /// <remarks>
        /// Valores medios mensuales y anuales de los datos climatológicos para la estación y el periodo de años pasados por parámetro. Periodicidad de actualización: 1 vez al día.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="anioIniStr">Año Inicial (AAAA)</param>
        /// <param name="anioFinStr">Año Final (AAAA)</param>
        /// <param name="idema">Indicativo climatológico de la EMA</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Model200</returns>
        ApiResponse<Model200> ClimatologasMensualesAnualesWithHttpInfo(string anioIniStr, string anioFinStr, string idema, int operationIndex = 0);
        /// <summary>
        /// Climatologías normales (1991-2020).
        /// </summary>
        /// <remarks>
        /// Valores climatológicos normales (periodo 1991-2020) para la estación pasada por parámetro. Periodicidad: 1 vez al día.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="idema">Indicativo climatológico de la EMA</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>Model200</returns>
        Model200 ClimatologasNormales19912020(string idema, int operationIndex = 0);

        /// <summary>
        /// Climatologías normales (1991-2020).
        /// </summary>
        /// <remarks>
        /// Valores climatológicos normales (periodo 1991-2020) para la estación pasada por parámetro. Periodicidad: 1 vez al día.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="idema">Indicativo climatológico de la EMA</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Model200</returns>
        ApiResponse<Model200> ClimatologasNormales19912020WithHttpInfo(string idema, int operationIndex = 0);
        /// <summary>
        /// Estaciones por indicativo.
        /// </summary>
        /// <remarks>
        /// Características de la estación climatológica pasada por parámetro.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="estaciones">Listado de indicativos climatológicos (id1,id2,id3,...,idn)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>Model200</returns>
        Model200 EstacionesPorIndicativo(string estaciones, int operationIndex = 0);

        /// <summary>
        /// Estaciones por indicativo.
        /// </summary>
        /// <remarks>
        /// Características de la estación climatológica pasada por parámetro.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="estaciones">Listado de indicativos climatológicos (id1,id2,id3,...,idn)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Model200</returns>
        ApiResponse<Model200> EstacionesPorIndicativoWithHttpInfo(string estaciones, int operationIndex = 0);
        /// <summary>
        /// Inventario de estaciones (valores climatológicos).
        /// </summary>
        /// <remarks>
        /// Inventario con las características de todas las estaciones climatológicas. Periodicidad: 1 vez al día.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>Model200</returns>
        Model200 InventarioDeEstacionesValoresClimatolgicos(int operationIndex = 0);

        /// <summary>
        /// Inventario de estaciones (valores climatológicos).
        /// </summary>
        /// <remarks>
        /// Inventario con las características de todas las estaciones climatológicas. Periodicidad: 1 vez al día.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Model200</returns>
        ApiResponse<Model200> InventarioDeEstacionesValoresClimatolgicosWithHttpInfo(int operationIndex = 0);
        /// <summary>
        /// Valores extremos.
        /// </summary>
        /// <remarks>
        /// Valores extremos para la estación y la variable (precipitación, temperatura y viento) pasadas por parámetro. Periodicidad: 1 vez al día.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="parametro"> | Código | Parámetro Meteorológico | |- -- -- -- -- -|- -- -- -- -- -| | P  | Precipitación   | | T  | Temperatura   | | V  | Viento </param>
        /// <param name="idema">Indicativo climatológico de la EMA</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>Model200</returns>
        Model200 ValoresExtremos(string parametro, string idema, int operationIndex = 0);

        /// <summary>
        /// Valores extremos.
        /// </summary>
        /// <remarks>
        /// Valores extremos para la estación y la variable (precipitación, temperatura y viento) pasadas por parámetro. Periodicidad: 1 vez al día.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="parametro"> | Código | Parámetro Meteorológico | |- -- -- -- -- -|- -- -- -- -- -| | P  | Precipitación   | | T  | Temperatura   | | V  | Viento </param>
        /// <param name="idema">Indicativo climatológico de la EMA</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Model200</returns>
        ApiResponse<Model200> ValoresExtremosWithHttpInfo(string parametro, string idema, int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IValoresClimatologicosApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Climatologías diarias.
        /// </summary>
        /// <remarks>
        /// Valores climatológicos para el rango de fechas y la estación seleccionada. Periodicidad: 1 vez al día.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="fechaIniStr">Fecha Inicial (AAAA-MM-DDTHH:MM:SSUTC)</param>
        /// <param name="fechaFinStr">Fecha Final (AAAA-MM-DDTHH:MM:SSUTC)</param>
        /// <param name="idema">Indicativo climatológico de la EMA. Puede introducir varios indicativos separados por comas (,)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Model200</returns>
        System.Threading.Tasks.Task<Model200> ClimatologasDiariasAsync(string fechaIniStr, string fechaFinStr, string idema, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Climatologías diarias.
        /// </summary>
        /// <remarks>
        /// Valores climatológicos para el rango de fechas y la estación seleccionada. Periodicidad: 1 vez al día.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="fechaIniStr">Fecha Inicial (AAAA-MM-DDTHH:MM:SSUTC)</param>
        /// <param name="fechaFinStr">Fecha Final (AAAA-MM-DDTHH:MM:SSUTC)</param>
        /// <param name="idema">Indicativo climatológico de la EMA. Puede introducir varios indicativos separados por comas (,)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Model200)</returns>
        System.Threading.Tasks.Task<ApiResponse<Model200>> ClimatologasDiariasWithHttpInfoAsync(string fechaIniStr, string fechaFinStr, string idema, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Climatologías diarias.
        /// </summary>
        /// <remarks>
        /// Valores climatológicos de todas las estaciones para el rango de fechas seleccionado. Periodicidad: 1 vez al día.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="fechaIniStr">Fecha Inicial (AAAA-MM-DDTHH:MM:SSUTC)</param>
        /// <param name="fechaFinStr">Fecha Final (AAAA-MM-DDTHH:MM:SSUTC)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Model200</returns>
        System.Threading.Tasks.Task<Model200> ClimatologasDiarias1Async(string fechaIniStr, string fechaFinStr, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Climatologías diarias.
        /// </summary>
        /// <remarks>
        /// Valores climatológicos de todas las estaciones para el rango de fechas seleccionado. Periodicidad: 1 vez al día.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="fechaIniStr">Fecha Inicial (AAAA-MM-DDTHH:MM:SSUTC)</param>
        /// <param name="fechaFinStr">Fecha Final (AAAA-MM-DDTHH:MM:SSUTC)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Model200)</returns>
        System.Threading.Tasks.Task<ApiResponse<Model200>> ClimatologasDiarias1WithHttpInfoAsync(string fechaIniStr, string fechaFinStr, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Climatologías mensuales anuales.
        /// </summary>
        /// <remarks>
        /// Valores medios mensuales y anuales de los datos climatológicos para la estación y el periodo de años pasados por parámetro. Periodicidad de actualización: 1 vez al día.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="anioIniStr">Año Inicial (AAAA)</param>
        /// <param name="anioFinStr">Año Final (AAAA)</param>
        /// <param name="idema">Indicativo climatológico de la EMA</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Model200</returns>
        System.Threading.Tasks.Task<Model200> ClimatologasMensualesAnualesAsync(string anioIniStr, string anioFinStr, string idema, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Climatologías mensuales anuales.
        /// </summary>
        /// <remarks>
        /// Valores medios mensuales y anuales de los datos climatológicos para la estación y el periodo de años pasados por parámetro. Periodicidad de actualización: 1 vez al día.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="anioIniStr">Año Inicial (AAAA)</param>
        /// <param name="anioFinStr">Año Final (AAAA)</param>
        /// <param name="idema">Indicativo climatológico de la EMA</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Model200)</returns>
        System.Threading.Tasks.Task<ApiResponse<Model200>> ClimatologasMensualesAnualesWithHttpInfoAsync(string anioIniStr, string anioFinStr, string idema, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Climatologías normales (1991-2020).
        /// </summary>
        /// <remarks>
        /// Valores climatológicos normales (periodo 1991-2020) para la estación pasada por parámetro. Periodicidad: 1 vez al día.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="idema">Indicativo climatológico de la EMA</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Model200</returns>
        System.Threading.Tasks.Task<Model200> ClimatologasNormales19912020Async(string idema, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Climatologías normales (1991-2020).
        /// </summary>
        /// <remarks>
        /// Valores climatológicos normales (periodo 1991-2020) para la estación pasada por parámetro. Periodicidad: 1 vez al día.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="idema">Indicativo climatológico de la EMA</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Model200)</returns>
        System.Threading.Tasks.Task<ApiResponse<Model200>> ClimatologasNormales19912020WithHttpInfoAsync(string idema, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Estaciones por indicativo.
        /// </summary>
        /// <remarks>
        /// Características de la estación climatológica pasada por parámetro.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="estaciones">Listado de indicativos climatológicos (id1,id2,id3,...,idn)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Model200</returns>
        System.Threading.Tasks.Task<Model200> EstacionesPorIndicativoAsync(string estaciones, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Estaciones por indicativo.
        /// </summary>
        /// <remarks>
        /// Características de la estación climatológica pasada por parámetro.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="estaciones">Listado de indicativos climatológicos (id1,id2,id3,...,idn)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Model200)</returns>
        System.Threading.Tasks.Task<ApiResponse<Model200>> EstacionesPorIndicativoWithHttpInfoAsync(string estaciones, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Inventario de estaciones (valores climatológicos).
        /// </summary>
        /// <remarks>
        /// Inventario con las características de todas las estaciones climatológicas. Periodicidad: 1 vez al día.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Model200</returns>
        System.Threading.Tasks.Task<Model200> InventarioDeEstacionesValoresClimatolgicosAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Inventario de estaciones (valores climatológicos).
        /// </summary>
        /// <remarks>
        /// Inventario con las características de todas las estaciones climatológicas. Periodicidad: 1 vez al día.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Model200)</returns>
        System.Threading.Tasks.Task<ApiResponse<Model200>> InventarioDeEstacionesValoresClimatolgicosWithHttpInfoAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Valores extremos.
        /// </summary>
        /// <remarks>
        /// Valores extremos para la estación y la variable (precipitación, temperatura y viento) pasadas por parámetro. Periodicidad: 1 vez al día.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="parametro"> | Código | Parámetro Meteorológico | |- -- -- -- -- -|- -- -- -- -- -| | P  | Precipitación   | | T  | Temperatura   | | V  | Viento </param>
        /// <param name="idema">Indicativo climatológico de la EMA</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Model200</returns>
        System.Threading.Tasks.Task<Model200> ValoresExtremosAsync(string parametro, string idema, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Valores extremos.
        /// </summary>
        /// <remarks>
        /// Valores extremos para la estación y la variable (precipitación, temperatura y viento) pasadas por parámetro. Periodicidad: 1 vez al día.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="parametro"> | Código | Parámetro Meteorológico | |- -- -- -- -- -|- -- -- -- -- -| | P  | Precipitación   | | T  | Temperatura   | | V  | Viento </param>
        /// <param name="idema">Indicativo climatológico de la EMA</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Model200)</returns>
        System.Threading.Tasks.Task<ApiResponse<Model200>> ValoresExtremosWithHttpInfoAsync(string parametro, string idema, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IValoresClimatologicosApi : IValoresClimatologicosApiSync, IValoresClimatologicosApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class ValoresClimatologicosApi : IValoresClimatologicosApi
    {
        private Org.OpenAPITools.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="ValoresClimatologicosApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ValoresClimatologicosApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ValoresClimatologicosApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ValoresClimatologicosApi(string basePath)
        {
            this.Configuration = Org.OpenAPITools.Client.Configuration.MergeConfigurations(
                Org.OpenAPITools.Client.GlobalConfiguration.Instance,
                new Org.OpenAPITools.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ValoresClimatologicosApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public ValoresClimatologicosApi(Org.OpenAPITools.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Org.OpenAPITools.Client.Configuration.MergeConfigurations(
                Org.OpenAPITools.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ValoresClimatologicosApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public ValoresClimatologicosApi(Org.OpenAPITools.Client.ISynchronousClient client, Org.OpenAPITools.Client.IAsynchronousClient asyncClient, Org.OpenAPITools.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Org.OpenAPITools.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Org.OpenAPITools.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Org.OpenAPITools.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Org.OpenAPITools.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Climatologías diarias. Valores climatológicos para el rango de fechas y la estación seleccionada. Periodicidad: 1 vez al día.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="fechaIniStr">Fecha Inicial (AAAA-MM-DDTHH:MM:SSUTC)</param>
        /// <param name="fechaFinStr">Fecha Final (AAAA-MM-DDTHH:MM:SSUTC)</param>
        /// <param name="idema">Indicativo climatológico de la EMA. Puede introducir varios indicativos separados por comas (,)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>Model200</returns>
        public Model200 ClimatologasDiarias(string fechaIniStr, string fechaFinStr, string idema, int operationIndex = 0)
        {
            Org.OpenAPITools.Client.ApiResponse<Model200> localVarResponse = ClimatologasDiariasWithHttpInfo(fechaIniStr, fechaFinStr, idema);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Climatologías diarias. Valores climatológicos para el rango de fechas y la estación seleccionada. Periodicidad: 1 vez al día.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="fechaIniStr">Fecha Inicial (AAAA-MM-DDTHH:MM:SSUTC)</param>
        /// <param name="fechaFinStr">Fecha Final (AAAA-MM-DDTHH:MM:SSUTC)</param>
        /// <param name="idema">Indicativo climatológico de la EMA. Puede introducir varios indicativos separados por comas (,)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Model200</returns>
        public Org.OpenAPITools.Client.ApiResponse<Model200> ClimatologasDiariasWithHttpInfo(string fechaIniStr, string fechaFinStr, string idema, int operationIndex = 0)
        {
            // verify the required parameter 'fechaIniStr' is set
            if (fechaIniStr == null)
            {
                throw new ApiException(400, "Missing required parameter 'fechaIniStr' when calling ValoresClimatologicosApi->ClimatologasDiarias");
            }

            // verify the required parameter 'fechaFinStr' is set
            if (fechaFinStr == null)
            {
                throw new ApiException(400, "Missing required parameter 'fechaFinStr' when calling ValoresClimatologicosApi->ClimatologasDiarias");
            }

            // verify the required parameter 'idema' is set
            if (idema == null)
            {
                throw new ApiException(400, "Missing required parameter 'idema' when calling ValoresClimatologicosApi->ClimatologasDiarias");
            }

            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("fechaIniStr", Org.OpenAPITools.Client.ClientUtils.ParameterToString(fechaIniStr)); // path parameter
            localVarRequestOptions.PathParameters.Add("fechaFinStr", Org.OpenAPITools.Client.ClientUtils.ParameterToString(fechaFinStr)); // path parameter
            localVarRequestOptions.PathParameters.Add("idema", Org.OpenAPITools.Client.ClientUtils.ParameterToString(idema)); // path parameter

            localVarRequestOptions.Operation = "ValoresClimatologicosApi.ClimatologasDiarias";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (api_key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("api_key")))
            {
                localVarRequestOptions.HeaderParameters.Add("api_key", this.Configuration.GetApiKeyWithPrefix("api_key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<Model200>("/api/valores/climatologicos/diarios/datos/fechaini/{fechaIniStr}/fechafin/{fechaFinStr}/estacion/{idema}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ClimatologasDiarias", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Climatologías diarias. Valores climatológicos para el rango de fechas y la estación seleccionada. Periodicidad: 1 vez al día.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="fechaIniStr">Fecha Inicial (AAAA-MM-DDTHH:MM:SSUTC)</param>
        /// <param name="fechaFinStr">Fecha Final (AAAA-MM-DDTHH:MM:SSUTC)</param>
        /// <param name="idema">Indicativo climatológico de la EMA. Puede introducir varios indicativos separados por comas (,)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Model200</returns>
        public async System.Threading.Tasks.Task<Model200> ClimatologasDiariasAsync(string fechaIniStr, string fechaFinStr, string idema, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Org.OpenAPITools.Client.ApiResponse<Model200> localVarResponse = await ClimatologasDiariasWithHttpInfoAsync(fechaIniStr, fechaFinStr, idema, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Climatologías diarias. Valores climatológicos para el rango de fechas y la estación seleccionada. Periodicidad: 1 vez al día.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="fechaIniStr">Fecha Inicial (AAAA-MM-DDTHH:MM:SSUTC)</param>
        /// <param name="fechaFinStr">Fecha Final (AAAA-MM-DDTHH:MM:SSUTC)</param>
        /// <param name="idema">Indicativo climatológico de la EMA. Puede introducir varios indicativos separados por comas (,)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Model200)</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<Model200>> ClimatologasDiariasWithHttpInfoAsync(string fechaIniStr, string fechaFinStr, string idema, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'fechaIniStr' is set
            if (fechaIniStr == null)
            {
                throw new ApiException(400, "Missing required parameter 'fechaIniStr' when calling ValoresClimatologicosApi->ClimatologasDiarias");
            }

            // verify the required parameter 'fechaFinStr' is set
            if (fechaFinStr == null)
            {
                throw new ApiException(400, "Missing required parameter 'fechaFinStr' when calling ValoresClimatologicosApi->ClimatologasDiarias");
            }

            // verify the required parameter 'idema' is set
            if (idema == null)
            {
                throw new ApiException(400, "Missing required parameter 'idema' when calling ValoresClimatologicosApi->ClimatologasDiarias");
            }


            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("fechaIniStr", Org.OpenAPITools.Client.ClientUtils.ParameterToString(fechaIniStr)); // path parameter
            localVarRequestOptions.PathParameters.Add("fechaFinStr", Org.OpenAPITools.Client.ClientUtils.ParameterToString(fechaFinStr)); // path parameter
            localVarRequestOptions.PathParameters.Add("idema", Org.OpenAPITools.Client.ClientUtils.ParameterToString(idema)); // path parameter

            localVarRequestOptions.Operation = "ValoresClimatologicosApi.ClimatologasDiarias";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (api_key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("api_key")))
            {
                localVarRequestOptions.HeaderParameters.Add("api_key", this.Configuration.GetApiKeyWithPrefix("api_key"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<Model200>("/api/valores/climatologicos/diarios/datos/fechaini/{fechaIniStr}/fechafin/{fechaFinStr}/estacion/{idema}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ClimatologasDiarias", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Climatologías diarias. Valores climatológicos de todas las estaciones para el rango de fechas seleccionado. Periodicidad: 1 vez al día.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="fechaIniStr">Fecha Inicial (AAAA-MM-DDTHH:MM:SSUTC)</param>
        /// <param name="fechaFinStr">Fecha Final (AAAA-MM-DDTHH:MM:SSUTC)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>Model200</returns>
        public Model200 ClimatologasDiarias1(string fechaIniStr, string fechaFinStr, int operationIndex = 0)
        {
            Org.OpenAPITools.Client.ApiResponse<Model200> localVarResponse = ClimatologasDiarias1WithHttpInfo(fechaIniStr, fechaFinStr);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Climatologías diarias. Valores climatológicos de todas las estaciones para el rango de fechas seleccionado. Periodicidad: 1 vez al día.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="fechaIniStr">Fecha Inicial (AAAA-MM-DDTHH:MM:SSUTC)</param>
        /// <param name="fechaFinStr">Fecha Final (AAAA-MM-DDTHH:MM:SSUTC)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Model200</returns>
        public Org.OpenAPITools.Client.ApiResponse<Model200> ClimatologasDiarias1WithHttpInfo(string fechaIniStr, string fechaFinStr, int operationIndex = 0)
        {
            // verify the required parameter 'fechaIniStr' is set
            if (fechaIniStr == null)
            {
                throw new ApiException(400, "Missing required parameter 'fechaIniStr' when calling ValoresClimatologicosApi->ClimatologasDiarias1");
            }

            // verify the required parameter 'fechaFinStr' is set
            if (fechaFinStr == null)
            {
                throw new ApiException(400, "Missing required parameter 'fechaFinStr' when calling ValoresClimatologicosApi->ClimatologasDiarias1");
            }

            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("fechaIniStr", Org.OpenAPITools.Client.ClientUtils.ParameterToString(fechaIniStr)); // path parameter
            localVarRequestOptions.PathParameters.Add("fechaFinStr", Org.OpenAPITools.Client.ClientUtils.ParameterToString(fechaFinStr)); // path parameter

            localVarRequestOptions.Operation = "ValoresClimatologicosApi.ClimatologasDiarias1";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (api_key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("api_key")))
            {
                localVarRequestOptions.HeaderParameters.Add("api_key", this.Configuration.GetApiKeyWithPrefix("api_key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<Model200>("/api/valores/climatologicos/diarios/datos/fechaini/{fechaIniStr}/fechafin/{fechaFinStr}/todasestaciones", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ClimatologasDiarias1", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Climatologías diarias. Valores climatológicos de todas las estaciones para el rango de fechas seleccionado. Periodicidad: 1 vez al día.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="fechaIniStr">Fecha Inicial (AAAA-MM-DDTHH:MM:SSUTC)</param>
        /// <param name="fechaFinStr">Fecha Final (AAAA-MM-DDTHH:MM:SSUTC)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Model200</returns>
        public async System.Threading.Tasks.Task<Model200> ClimatologasDiarias1Async(string fechaIniStr, string fechaFinStr, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Org.OpenAPITools.Client.ApiResponse<Model200> localVarResponse = await ClimatologasDiarias1WithHttpInfoAsync(fechaIniStr, fechaFinStr, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Climatologías diarias. Valores climatológicos de todas las estaciones para el rango de fechas seleccionado. Periodicidad: 1 vez al día.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="fechaIniStr">Fecha Inicial (AAAA-MM-DDTHH:MM:SSUTC)</param>
        /// <param name="fechaFinStr">Fecha Final (AAAA-MM-DDTHH:MM:SSUTC)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Model200)</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<Model200>> ClimatologasDiarias1WithHttpInfoAsync(string fechaIniStr, string fechaFinStr, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'fechaIniStr' is set
            if (fechaIniStr == null)
            {
                throw new ApiException(400, "Missing required parameter 'fechaIniStr' when calling ValoresClimatologicosApi->ClimatologasDiarias1");
            }

            // verify the required parameter 'fechaFinStr' is set
            if (fechaFinStr == null)
            {
                throw new ApiException(400, "Missing required parameter 'fechaFinStr' when calling ValoresClimatologicosApi->ClimatologasDiarias1");
            }


            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("fechaIniStr", Org.OpenAPITools.Client.ClientUtils.ParameterToString(fechaIniStr)); // path parameter
            localVarRequestOptions.PathParameters.Add("fechaFinStr", Org.OpenAPITools.Client.ClientUtils.ParameterToString(fechaFinStr)); // path parameter

            localVarRequestOptions.Operation = "ValoresClimatologicosApi.ClimatologasDiarias1";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (api_key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("api_key")))
            {
                localVarRequestOptions.HeaderParameters.Add("api_key", this.Configuration.GetApiKeyWithPrefix("api_key"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<Model200>("/api/valores/climatologicos/diarios/datos/fechaini/{fechaIniStr}/fechafin/{fechaFinStr}/todasestaciones", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ClimatologasDiarias1", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Climatologías mensuales anuales. Valores medios mensuales y anuales de los datos climatológicos para la estación y el periodo de años pasados por parámetro. Periodicidad de actualización: 1 vez al día.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="anioIniStr">Año Inicial (AAAA)</param>
        /// <param name="anioFinStr">Año Final (AAAA)</param>
        /// <param name="idema">Indicativo climatológico de la EMA</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>Model200</returns>
        public Model200 ClimatologasMensualesAnuales(string anioIniStr, string anioFinStr, string idema, int operationIndex = 0)
        {
            Org.OpenAPITools.Client.ApiResponse<Model200> localVarResponse = ClimatologasMensualesAnualesWithHttpInfo(anioIniStr, anioFinStr, idema);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Climatologías mensuales anuales. Valores medios mensuales y anuales de los datos climatológicos para la estación y el periodo de años pasados por parámetro. Periodicidad de actualización: 1 vez al día.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="anioIniStr">Año Inicial (AAAA)</param>
        /// <param name="anioFinStr">Año Final (AAAA)</param>
        /// <param name="idema">Indicativo climatológico de la EMA</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Model200</returns>
        public Org.OpenAPITools.Client.ApiResponse<Model200> ClimatologasMensualesAnualesWithHttpInfo(string anioIniStr, string anioFinStr, string idema, int operationIndex = 0)
        {
            // verify the required parameter 'anioIniStr' is set
            if (anioIniStr == null)
            {
                throw new ApiException(400, "Missing required parameter 'anioIniStr' when calling ValoresClimatologicosApi->ClimatologasMensualesAnuales");
            }

            // verify the required parameter 'anioFinStr' is set
            if (anioFinStr == null)
            {
                throw new ApiException(400, "Missing required parameter 'anioFinStr' when calling ValoresClimatologicosApi->ClimatologasMensualesAnuales");
            }

            // verify the required parameter 'idema' is set
            if (idema == null)
            {
                throw new ApiException(400, "Missing required parameter 'idema' when calling ValoresClimatologicosApi->ClimatologasMensualesAnuales");
            }

            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("anioIniStr", Org.OpenAPITools.Client.ClientUtils.ParameterToString(anioIniStr)); // path parameter
            localVarRequestOptions.PathParameters.Add("anioFinStr", Org.OpenAPITools.Client.ClientUtils.ParameterToString(anioFinStr)); // path parameter
            localVarRequestOptions.PathParameters.Add("idema", Org.OpenAPITools.Client.ClientUtils.ParameterToString(idema)); // path parameter

            localVarRequestOptions.Operation = "ValoresClimatologicosApi.ClimatologasMensualesAnuales";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (api_key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("api_key")))
            {
                localVarRequestOptions.HeaderParameters.Add("api_key", this.Configuration.GetApiKeyWithPrefix("api_key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<Model200>("/api/valores/climatologicos/mensualesanuales/datos/anioini/{anioIniStr}/aniofin/{anioFinStr}/estacion/{idema}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ClimatologasMensualesAnuales", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Climatologías mensuales anuales. Valores medios mensuales y anuales de los datos climatológicos para la estación y el periodo de años pasados por parámetro. Periodicidad de actualización: 1 vez al día.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="anioIniStr">Año Inicial (AAAA)</param>
        /// <param name="anioFinStr">Año Final (AAAA)</param>
        /// <param name="idema">Indicativo climatológico de la EMA</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Model200</returns>
        public async System.Threading.Tasks.Task<Model200> ClimatologasMensualesAnualesAsync(string anioIniStr, string anioFinStr, string idema, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Org.OpenAPITools.Client.ApiResponse<Model200> localVarResponse = await ClimatologasMensualesAnualesWithHttpInfoAsync(anioIniStr, anioFinStr, idema, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Climatologías mensuales anuales. Valores medios mensuales y anuales de los datos climatológicos para la estación y el periodo de años pasados por parámetro. Periodicidad de actualización: 1 vez al día.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="anioIniStr">Año Inicial (AAAA)</param>
        /// <param name="anioFinStr">Año Final (AAAA)</param>
        /// <param name="idema">Indicativo climatológico de la EMA</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Model200)</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<Model200>> ClimatologasMensualesAnualesWithHttpInfoAsync(string anioIniStr, string anioFinStr, string idema, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'anioIniStr' is set
            if (anioIniStr == null)
            {
                throw new ApiException(400, "Missing required parameter 'anioIniStr' when calling ValoresClimatologicosApi->ClimatologasMensualesAnuales");
            }

            // verify the required parameter 'anioFinStr' is set
            if (anioFinStr == null)
            {
                throw new ApiException(400, "Missing required parameter 'anioFinStr' when calling ValoresClimatologicosApi->ClimatologasMensualesAnuales");
            }

            // verify the required parameter 'idema' is set
            if (idema == null)
            {
                throw new ApiException(400, "Missing required parameter 'idema' when calling ValoresClimatologicosApi->ClimatologasMensualesAnuales");
            }


            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("anioIniStr", Org.OpenAPITools.Client.ClientUtils.ParameterToString(anioIniStr)); // path parameter
            localVarRequestOptions.PathParameters.Add("anioFinStr", Org.OpenAPITools.Client.ClientUtils.ParameterToString(anioFinStr)); // path parameter
            localVarRequestOptions.PathParameters.Add("idema", Org.OpenAPITools.Client.ClientUtils.ParameterToString(idema)); // path parameter

            localVarRequestOptions.Operation = "ValoresClimatologicosApi.ClimatologasMensualesAnuales";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (api_key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("api_key")))
            {
                localVarRequestOptions.HeaderParameters.Add("api_key", this.Configuration.GetApiKeyWithPrefix("api_key"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<Model200>("/api/valores/climatologicos/mensualesanuales/datos/anioini/{anioIniStr}/aniofin/{anioFinStr}/estacion/{idema}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ClimatologasMensualesAnuales", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Climatologías normales (1991-2020). Valores climatológicos normales (periodo 1991-2020) para la estación pasada por parámetro. Periodicidad: 1 vez al día.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="idema">Indicativo climatológico de la EMA</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>Model200</returns>
        public Model200 ClimatologasNormales19912020(string idema, int operationIndex = 0)
        {
            Org.OpenAPITools.Client.ApiResponse<Model200> localVarResponse = ClimatologasNormales19912020WithHttpInfo(idema);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Climatologías normales (1991-2020). Valores climatológicos normales (periodo 1991-2020) para la estación pasada por parámetro. Periodicidad: 1 vez al día.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="idema">Indicativo climatológico de la EMA</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Model200</returns>
        public Org.OpenAPITools.Client.ApiResponse<Model200> ClimatologasNormales19912020WithHttpInfo(string idema, int operationIndex = 0)
        {
            // verify the required parameter 'idema' is set
            if (idema == null)
            {
                throw new ApiException(400, "Missing required parameter 'idema' when calling ValoresClimatologicosApi->ClimatologasNormales19912020");
            }

            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("idema", Org.OpenAPITools.Client.ClientUtils.ParameterToString(idema)); // path parameter

            localVarRequestOptions.Operation = "ValoresClimatologicosApi.ClimatologasNormales19912020";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (api_key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("api_key")))
            {
                localVarRequestOptions.HeaderParameters.Add("api_key", this.Configuration.GetApiKeyWithPrefix("api_key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<Model200>("/api/valores/climatologicos/normales/estacion/{idema}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ClimatologasNormales19912020", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Climatologías normales (1991-2020). Valores climatológicos normales (periodo 1991-2020) para la estación pasada por parámetro. Periodicidad: 1 vez al día.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="idema">Indicativo climatológico de la EMA</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Model200</returns>
        public async System.Threading.Tasks.Task<Model200> ClimatologasNormales19912020Async(string idema, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Org.OpenAPITools.Client.ApiResponse<Model200> localVarResponse = await ClimatologasNormales19912020WithHttpInfoAsync(idema, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Climatologías normales (1991-2020). Valores climatológicos normales (periodo 1991-2020) para la estación pasada por parámetro. Periodicidad: 1 vez al día.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="idema">Indicativo climatológico de la EMA</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Model200)</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<Model200>> ClimatologasNormales19912020WithHttpInfoAsync(string idema, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'idema' is set
            if (idema == null)
            {
                throw new ApiException(400, "Missing required parameter 'idema' when calling ValoresClimatologicosApi->ClimatologasNormales19912020");
            }


            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("idema", Org.OpenAPITools.Client.ClientUtils.ParameterToString(idema)); // path parameter

            localVarRequestOptions.Operation = "ValoresClimatologicosApi.ClimatologasNormales19912020";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (api_key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("api_key")))
            {
                localVarRequestOptions.HeaderParameters.Add("api_key", this.Configuration.GetApiKeyWithPrefix("api_key"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<Model200>("/api/valores/climatologicos/normales/estacion/{idema}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ClimatologasNormales19912020", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Estaciones por indicativo. Características de la estación climatológica pasada por parámetro.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="estaciones">Listado de indicativos climatológicos (id1,id2,id3,...,idn)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>Model200</returns>
        public Model200 EstacionesPorIndicativo(string estaciones, int operationIndex = 0)
        {
            Org.OpenAPITools.Client.ApiResponse<Model200> localVarResponse = EstacionesPorIndicativoWithHttpInfo(estaciones);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Estaciones por indicativo. Características de la estación climatológica pasada por parámetro.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="estaciones">Listado de indicativos climatológicos (id1,id2,id3,...,idn)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Model200</returns>
        public Org.OpenAPITools.Client.ApiResponse<Model200> EstacionesPorIndicativoWithHttpInfo(string estaciones, int operationIndex = 0)
        {
            // verify the required parameter 'estaciones' is set
            if (estaciones == null)
            {
                throw new ApiException(400, "Missing required parameter 'estaciones' when calling ValoresClimatologicosApi->EstacionesPorIndicativo");
            }

            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("estaciones", Org.OpenAPITools.Client.ClientUtils.ParameterToString(estaciones)); // path parameter

            localVarRequestOptions.Operation = "ValoresClimatologicosApi.EstacionesPorIndicativo";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (api_key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("api_key")))
            {
                localVarRequestOptions.HeaderParameters.Add("api_key", this.Configuration.GetApiKeyWithPrefix("api_key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<Model200>("/api/valores/climatologicos/inventarioestaciones/estaciones/{estaciones}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("EstacionesPorIndicativo", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Estaciones por indicativo. Características de la estación climatológica pasada por parámetro.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="estaciones">Listado de indicativos climatológicos (id1,id2,id3,...,idn)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Model200</returns>
        public async System.Threading.Tasks.Task<Model200> EstacionesPorIndicativoAsync(string estaciones, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Org.OpenAPITools.Client.ApiResponse<Model200> localVarResponse = await EstacionesPorIndicativoWithHttpInfoAsync(estaciones, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Estaciones por indicativo. Características de la estación climatológica pasada por parámetro.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="estaciones">Listado de indicativos climatológicos (id1,id2,id3,...,idn)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Model200)</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<Model200>> EstacionesPorIndicativoWithHttpInfoAsync(string estaciones, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'estaciones' is set
            if (estaciones == null)
            {
                throw new ApiException(400, "Missing required parameter 'estaciones' when calling ValoresClimatologicosApi->EstacionesPorIndicativo");
            }


            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("estaciones", Org.OpenAPITools.Client.ClientUtils.ParameterToString(estaciones)); // path parameter

            localVarRequestOptions.Operation = "ValoresClimatologicosApi.EstacionesPorIndicativo";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (api_key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("api_key")))
            {
                localVarRequestOptions.HeaderParameters.Add("api_key", this.Configuration.GetApiKeyWithPrefix("api_key"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<Model200>("/api/valores/climatologicos/inventarioestaciones/estaciones/{estaciones}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("EstacionesPorIndicativo", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Inventario de estaciones (valores climatológicos). Inventario con las características de todas las estaciones climatológicas. Periodicidad: 1 vez al día.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>Model200</returns>
        public Model200 InventarioDeEstacionesValoresClimatolgicos(int operationIndex = 0)
        {
            Org.OpenAPITools.Client.ApiResponse<Model200> localVarResponse = InventarioDeEstacionesValoresClimatolgicosWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        /// Inventario de estaciones (valores climatológicos). Inventario con las características de todas las estaciones climatológicas. Periodicidad: 1 vez al día.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Model200</returns>
        public Org.OpenAPITools.Client.ApiResponse<Model200> InventarioDeEstacionesValoresClimatolgicosWithHttpInfo(int operationIndex = 0)
        {
            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }


            localVarRequestOptions.Operation = "ValoresClimatologicosApi.InventarioDeEstacionesValoresClimatolgicos";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (api_key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("api_key")))
            {
                localVarRequestOptions.HeaderParameters.Add("api_key", this.Configuration.GetApiKeyWithPrefix("api_key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<Model200>("/api/valores/climatologicos/inventarioestaciones/todasestaciones", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("InventarioDeEstacionesValoresClimatolgicos", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Inventario de estaciones (valores climatológicos). Inventario con las características de todas las estaciones climatológicas. Periodicidad: 1 vez al día.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Model200</returns>
        public async System.Threading.Tasks.Task<Model200> InventarioDeEstacionesValoresClimatolgicosAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Org.OpenAPITools.Client.ApiResponse<Model200> localVarResponse = await InventarioDeEstacionesValoresClimatolgicosWithHttpInfoAsync(operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Inventario de estaciones (valores climatológicos). Inventario con las características de todas las estaciones climatológicas. Periodicidad: 1 vez al día.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Model200)</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<Model200>> InventarioDeEstacionesValoresClimatolgicosWithHttpInfoAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }


            localVarRequestOptions.Operation = "ValoresClimatologicosApi.InventarioDeEstacionesValoresClimatolgicos";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (api_key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("api_key")))
            {
                localVarRequestOptions.HeaderParameters.Add("api_key", this.Configuration.GetApiKeyWithPrefix("api_key"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<Model200>("/api/valores/climatologicos/inventarioestaciones/todasestaciones", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("InventarioDeEstacionesValoresClimatolgicos", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Valores extremos. Valores extremos para la estación y la variable (precipitación, temperatura y viento) pasadas por parámetro. Periodicidad: 1 vez al día.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="parametro"> | Código | Parámetro Meteorológico | |- -- -- -- -- -|- -- -- -- -- -| | P  | Precipitación   | | T  | Temperatura   | | V  | Viento </param>
        /// <param name="idema">Indicativo climatológico de la EMA</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>Model200</returns>
        public Model200 ValoresExtremos(string parametro, string idema, int operationIndex = 0)
        {
            Org.OpenAPITools.Client.ApiResponse<Model200> localVarResponse = ValoresExtremosWithHttpInfo(parametro, idema);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Valores extremos. Valores extremos para la estación y la variable (precipitación, temperatura y viento) pasadas por parámetro. Periodicidad: 1 vez al día.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="parametro"> | Código | Parámetro Meteorológico | |- -- -- -- -- -|- -- -- -- -- -| | P  | Precipitación   | | T  | Temperatura   | | V  | Viento </param>
        /// <param name="idema">Indicativo climatológico de la EMA</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Model200</returns>
        public Org.OpenAPITools.Client.ApiResponse<Model200> ValoresExtremosWithHttpInfo(string parametro, string idema, int operationIndex = 0)
        {
            // verify the required parameter 'parametro' is set
            if (parametro == null)
            {
                throw new ApiException(400, "Missing required parameter 'parametro' when calling ValoresClimatologicosApi->ValoresExtremos");
            }

            // verify the required parameter 'idema' is set
            if (idema == null)
            {
                throw new ApiException(400, "Missing required parameter 'idema' when calling ValoresClimatologicosApi->ValoresExtremos");
            }

            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("parametro", Org.OpenAPITools.Client.ClientUtils.ParameterToString(parametro)); // path parameter
            localVarRequestOptions.PathParameters.Add("idema", Org.OpenAPITools.Client.ClientUtils.ParameterToString(idema)); // path parameter

            localVarRequestOptions.Operation = "ValoresClimatologicosApi.ValoresExtremos";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (api_key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("api_key")))
            {
                localVarRequestOptions.HeaderParameters.Add("api_key", this.Configuration.GetApiKeyWithPrefix("api_key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<Model200>("/api/valores/climatologicos/valoresextremos/parametro/{parametro}/estacion/{idema}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ValoresExtremos", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Valores extremos. Valores extremos para la estación y la variable (precipitación, temperatura y viento) pasadas por parámetro. Periodicidad: 1 vez al día.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="parametro"> | Código | Parámetro Meteorológico | |- -- -- -- -- -|- -- -- -- -- -| | P  | Precipitación   | | T  | Temperatura   | | V  | Viento </param>
        /// <param name="idema">Indicativo climatológico de la EMA</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Model200</returns>
        public async System.Threading.Tasks.Task<Model200> ValoresExtremosAsync(string parametro, string idema, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Org.OpenAPITools.Client.ApiResponse<Model200> localVarResponse = await ValoresExtremosWithHttpInfoAsync(parametro, idema, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Valores extremos. Valores extremos para la estación y la variable (precipitación, temperatura y viento) pasadas por parámetro. Periodicidad: 1 vez al día.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="parametro"> | Código | Parámetro Meteorológico | |- -- -- -- -- -|- -- -- -- -- -| | P  | Precipitación   | | T  | Temperatura   | | V  | Viento </param>
        /// <param name="idema">Indicativo climatológico de la EMA</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Model200)</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<Model200>> ValoresExtremosWithHttpInfoAsync(string parametro, string idema, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'parametro' is set
            if (parametro == null)
            {
                throw new ApiException(400, "Missing required parameter 'parametro' when calling ValoresClimatologicosApi->ValoresExtremos");
            }

            // verify the required parameter 'idema' is set
            if (idema == null)
            {
                throw new ApiException(400, "Missing required parameter 'idema' when calling ValoresClimatologicosApi->ValoresExtremos");
            }


            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("parametro", Org.OpenAPITools.Client.ClientUtils.ParameterToString(parametro)); // path parameter
            localVarRequestOptions.PathParameters.Add("idema", Org.OpenAPITools.Client.ClientUtils.ParameterToString(idema)); // path parameter

            localVarRequestOptions.Operation = "ValoresClimatologicosApi.ValoresExtremos";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (api_key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("api_key")))
            {
                localVarRequestOptions.HeaderParameters.Add("api_key", this.Configuration.GetApiKeyWithPrefix("api_key"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<Model200>("/api/valores/climatologicos/valoresextremos/parametro/{parametro}/estacion/{idema}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ValoresExtremos", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
