<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <ServerGarbageCollection>true</ServerGarbageCollection>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
        <DoNotCopyLocalIfInGac>true</DoNotCopyLocalIfInGac>
        <Description>Entorno modular para .NET 8 basado en Blazor y Radzen. Núcleo reutilizable para apps y servicios.</Description>
        <PackageTags>horizonte;blazor;radzen;modular;net8;framework</PackageTags>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
      <DebugType>embedded</DebugType>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
      <DebugSymbols>true</DebugSymbols>
      <DebugType>embedded</DebugType>
    </PropertyGroup>
    <ItemGroup>
        <None Remove="logconfig.xml"/>
        <None Remove="defaults.json"/>
        <Compile Remove="Interfaces\IHModManager.cs" />
        <Compile Remove="Services\HModManager.cs" />
    </ItemGroup>
    <ItemGroup>
      <None Include="README.md" Pack="true" PackagePath="/" />
    </ItemGroup>
    <ItemGroup>
      <PackageReference Include="Gelf4Net" Version="3.0.1.2" />
      <PackageReference Include="Microsoft.Extensions.DependencyModel" Version="10.0.1" />
      <PackageReference Include="Microsoft.Extensions.Logging.Log4Net.AspNetCore" Version="8.0.0" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.1" />
      <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.1" />
      <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.1" />


<!--
    -->    
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Features" Version="5.0.0" />
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="5.0.0" />
        <PackageReference Include="Microsoft.CodeAnalysis.VisualBasic.Features" Version="5.0.0" />
        <PackageReference Include="Microsoft.CodeAnalysis.VisualBasic.Workspaces" Version="5.0.0" />
        <PackageReference Include="Microsoft.CodeAnalysis.Compilers" Version="5.0.0" />
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.0.0" />
        <PackageReference Include="Microsoft.CodeAnalysis.VisualBasic" Version="5.0.0" />
        <PackageReference Include="Microsoft.CodeAnalysis.Scripting" Version="5.0.0" />
    </ItemGroup>

</Project>
