<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <ServerGarbageCollection>true</ServerGarbageCollection>
        <Description>Entorno modular para .NET 8 basado en Blazor y Radzen. Núcleo reutilizable para apps y servicios.</Description>
        <PackageTags>horizonte;blazor;radzen;modular;net8;framework</PackageTags>
        <JsonSerializerIsReflectionEnabledByDefault>true</JsonSerializerIsReflectionEnabledByDefault>
    </PropertyGroup>

    <ItemGroup>
        <None Remove="logconfig.xml"/>
        <None Remove="defaults.json"/>
        <Compile Remove="Interfaces\IHModManager.cs" />
        <Compile Remove="Services\HModManager.cs" />
    </ItemGroup>
    <ItemGroup>
      <PackageReference Include="Gelf4Net" Version="3.0.1.2" />
      <PackageReference Include="Microsoft.Extensions.DependencyModel" Version="10.0.1" />
      <PackageReference Include="Microsoft.Extensions.Logging.Log4Net.AspNetCore" Version="10.0.0" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.1" />
      <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.1" />
      <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.1" />



    </ItemGroup>

</Project>
