/*
 * AEMET OpenData
 *
 * AEMET OpenData es una API REST desarrollado por AEMET que permite la difusión y la reutilización de la información meteorológica y climatológica de la Agencia, en el sentido indicado en la Ley 18/2015, de 9 de julio, por la que se modifica la Ley 37/2007, de 16 de noviembre, sobre reutilización de la información del sector público. (IMPORTANTE: Para poder realizar peticiones, es necesario introducir en API Key haciendo clic en el círculo rojo de recurso REST).<br><br>`IMPORTANTE`: Para poder realizar peticiones, es necesario introducir el `api_key` y haciendo clic en el botón `'Authorize'`. Después pulse en el botón `'Try it out'´ del recurso que quiera consultar.
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Model404
    /// </summary>
    [DataContract(Name = "404")]
    public partial class Model404 : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Model404" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Model404() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Model404" /> class.
        /// </summary>
        /// <param name="descripcion">descripcion (required) (default to &quot;Not Found&quot;).</param>
        /// <param name="estado">estado (required).</param>
        public Model404(string descripcion = @"Not Found", int estado = default(int))
        {
            // to ensure "descripcion" is required (not null)
            if (descripcion == null)
            {
                throw new ArgumentNullException("descripcion is a required property for Model404 and cannot be null");
            }
            this.Descripcion = descripcion;
            this.Estado = estado;
        }

        /// <summary>
        /// Gets or Sets Descripcion
        /// </summary>
        [DataMember(Name = "descripcion", IsRequired = true, EmitDefaultValue = true)]
        public string Descripcion { get; set; }

        /// <summary>
        /// Gets or Sets Estado
        /// </summary>
        [DataMember(Name = "estado", IsRequired = true, EmitDefaultValue = true)]
        public int Estado { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Model404 {\n");
            sb.Append("  Descripcion: ").Append(Descripcion).Append("\n");
            sb.Append("  Estado: ").Append(Estado).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
