<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <OutputType>Library</OutputType>
      <IsPackable>true</IsPackable>
    </PropertyGroup>

    <ItemGroup Condition="'$(UseProjectReferences)' == 'true'">
        <ProjectReference Include="..\Horizonte\Horizonte.csproj" />
    </ItemGroup>
    <ItemGroup Condition="'$(UseProjectReferences)' == 'false'">
        <PackageReference Include="Horizonte" Version="$(InternalPackageVersion)" />
    </ItemGroup>

</Project>
