<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <NoDefaultLaunchSettingsFile>True</NoDefaultLaunchSettingsFile>
        <OutputType>Library</OutputType>
        <IsPackable>true</IsPackable>
    </PropertyGroup>

 
    <ItemGroup>
      <ProjectReference Include="..\AdminUi.Components\AdminUi.Components.csproj" />
      <ProjectReference Include="..\Horizonte.Extension.AspNetCore\Horizonte.Extension.AspNetCore.csproj" />
      <ProjectReference Include="..\Horizonte\Horizonte.csproj" />
        <PackageReference Include="Blazor.Monaco" Version="0.2.0" />
    </ItemGroup>
    
 


    <ItemGroup>
      <Folder Include="wwwroot\" />
    </ItemGroup>

    <ItemGroup>
      <Content Update="wwwroot\app.css">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </Content>
      <Content Update="wwwroot\blazor.web.js">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </Content>
      <Content Update="wwwroot\MainLayout.css">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="BlazorMonaco" Version="3.4.0" />
    </ItemGroup>




</Project>
