<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <OutputType>Library</OutputType>
        <IsPackable>true</IsPackable>
    </PropertyGroup>


    <ItemGroup>
        <SupportedPlatform Include="browser"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Horizonte\Horizonte.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Radzen.Blazor" Version="8.4.2" />
      <PackageReference Include="Swashbuckle.AspNetCore" Version="8.1.4" />
    </ItemGroup>



</Project>
