<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>



    <ItemGroup>
      <Folder Include="wwwroot\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Horizonte.Extension.AiWorkFlows\Horizonte.Extension.AiWorkFlows.csproj" />
      <ProjectReference Include="..\Horizonte\Horizonte.csproj" />
        <ProjectReference Include="..\AdminUi.Components\AdminUi.Components.csproj" />
    </ItemGroup>



</Project>
