<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>


    <ItemGroup>
        <SupportedPlatform Include="browser"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.1"/>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="wwwroot\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Horizonte.Extension.Ai\Horizonte.Extension.Ai.csproj" />
      <ProjectReference Include="..\Horizonte\Horizonte.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="Radzen.Blazor">
        <HintPath>..\..\..\..\f.fuster\.nuget\packages\radzen.blazor\8.4.2\lib\net10.0\Radzen.Blazor.dll</HintPath>
      </Reference>
    </ItemGroup>

</Project>
