<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <PackageTags>experimental;preview</PackageTags>
    </PropertyGroup>


    <ItemGroup>
        <Folder Include="wwwroot\"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Horizonte\Horizonte.csproj"/>
        <ProjectReference Include="..\Horizonte.Extension.AiWorkFlows\Horizonte.Extension.AiWorkFlows.csproj"/>
        <ProjectReference Include="..\AdminUi.Components\AdminUi.Components.csproj"/>
    </ItemGroup>
    <ItemGroup Condition="'$(UseProjectReferences)' == 'false'">
        <PackageReference Include="Horizonte" Version="$(InternalPackageVersion)" />
        <PackageReference Include="Horizonte.Extension.AiWorkFlows" Version="$(InternalPackageVersion)" />
        <PackageReference Include="AdminUi.Components" Version="$(InternalPackageVersion)" />
    </ItemGroup>


</Project>
