<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <OutputType>Library</OutputType>
    </PropertyGroup>

    <ItemGroup Condition="'$(UseProjectReferences)' == 'true'">
      <ProjectReference Include="..\AdminUi.Components\AdminUi.Components.csproj" />
      <ProjectReference Include="..\Horizonte\Horizonte.csproj" />
    </ItemGroup>
    <ItemGroup Condition="'$(UseProjectReferences)' == 'false'">
        <PackageReference Include="AdminUi.Components" Version="$(InternalPackageVersion)"/>
        <PackageReference Include="Horizonte" Version="$(InternalPackageVersion)"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="GoogleApi" Version="5.8.11" />
    </ItemGroup>


    <ItemGroup>

    </ItemGroup>

   

</Project>
