<Project Sdk="Microsoft.NET.Sdk.Web">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <OutputType>Library</OutputType>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="GtkSharp" Version="3.24.24.95" />
    </ItemGroup>

    <ItemGroup Condition="'$(UseProjectReferences)' == 'true'">
        <ProjectReference Include="..\AdminUi.Components\AdminUi.Components.csproj"/>
        <ProjectReference Include="..\Horizonte\Horizonte.csproj"/>
    </ItemGroup>
    <ItemGroup Condition="'$(UseProjectReferences)' == 'false'">
        <PackageReference Include="Horizonte" Version="$(InternalPackageVersion)"/>
        <PackageReference Include="AdminUi.Components" Version="$(InternalPackageVersion)"/>
    </ItemGroup>

    <ItemGroup>
      <None Remove="icon.png" />
      <None Remove="system.png" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="icons\home.png" />
      <EmbeddedResource Include="icons\home.png" />
      <None Remove="icons\netapp.png" />
      <EmbeddedResource Include="icons\netapp.png" />
      <None Remove="icons\red.png" />
      <EmbeddedResource Include="icons\red.png" />
      <None Remove="icons\work.png" />
      <EmbeddedResource Include="icons\work.png" />
      <None Remove="icons\works.png" />
      <EmbeddedResource Include="icons\works.png" />
    </ItemGroup>

</Project>
