<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PackageTags>experimental;preview</PackageTags>
    </PropertyGroup>
    <ItemGroup Condition="'$(UseProjectReferences)' == 'true'">
        <ProjectReference Include="..\Horizonte.Extension.Ai\Horizonte.Extension.Ai.csproj" />
        <ProjectReference Include="..\Horizonte\Horizonte.csproj"/>
        <ProjectReference Include="..\AdminUi.Components\AdminUi.Components.csproj"/>
    </ItemGroup>
    <ItemGroup Condition="'$(UseProjectReferences)' == 'false'">
        <PackageReference Include="Horizonte.Extension.Ai" Version="$(InternalPackageVersion)" />
        <PackageReference Include="Horizonte" Version="$(InternalPackageVersion)"/>
        <PackageReference Include="AdminUi.Components" Version="$(InternalPackageVersion)"/>
    </ItemGroup>
</Project>
