<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <OutputType>Library</OutputType>
        <NoDefaultLaunchSettingsFile>True</NoDefaultLaunchSettingsFile>
        <!-- Propiedades necesarias para empaquetar NuGet -->
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild> <!-- Habilita la creación del paquete al compilar -->
        <Description>Ejemplos de aplicaciones Razor utilizando Horizonte.</Description> <!-- Descripción del paquete -->
        <PackageTags>horizonte;razor;samples</PackageTags> <!-- Etiquetas relacionadas con el paquete -->
        <IsPackable>true</IsPackable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Horizonte.Extension.AspNetCore\Horizonte.Extension.AspNetCore.csproj" />
      <ProjectReference Include="..\Horizonte\Horizonte.csproj" />
      <ProjectReference Include="..\Horizonte.Samples.SampleComponent\Horizonte.Samples.SampleComponent.csproj" />
        <ProjectReference Include="..\AdminUi.Components\AdminUi.Components.csproj" />
        
    </ItemGroup>
    <ItemGroup>
        <None Include="wwwroot\**" CopyToOutputDirectory="Always" />
        <Compile Remove="HorizonteStaticFileContext.cs" />
    </ItemGroup>
    <ItemGroup>
      <PackageReference Include="Radzen.Blazor" Version="8.4.2" />
    </ItemGroup>

</Project>
