<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup Condition="'$(UseProjectReferences)' == 'true'">
      <ProjectReference Include="..\AdminUi.Components\AdminUi.Components.csproj" />
      <ProjectReference Include="..\Horizonte\Horizonte.csproj" />
    </ItemGroup>
    <ItemGroup Condition="'$(UseProjectReferences)' == 'false'">
        <PackageReference Include="AdminUi.Components" Version="$(InternalPackageVersion)" />
        <PackageReference Include="Horizonte" Version="$(InternalPackageVersion)" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="PvRecorder" Version="1.2.13" />
        <PackageReference Include="Porcupine" Version="4.0.1" />
    </ItemGroup>
    <ItemGroup>
      <Folder Include="wwwroot\" />
    </ItemGroup>
</Project>
