<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <OutputType>Library</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Radzen.Blazor" Version="8.4.2"/>
    </ItemGroup>
    
    <ItemGroup Condition="'$(UseProjectReferences)' == 'true'">
        <ProjectReference Include="..\Horizonte\Horizonte.csproj"/>
        <ProjectReference Include="..\Horizonte.Extension.AspNetCore\Horizonte.Extension.AspNetCore.csproj"/>
    </ItemGroup>
    <ItemGroup Condition="'$(UseProjectReferences)' == 'false'">
        <PackageReference Include="Horizonte" Version="$(InternalPackageVersion)"/>
        <PackageReference Include="Horizonte.Extension.AspNetCore" Version="$(InternalPackageVersion)"/>
    </ItemGroup>
    
    <ItemGroup>
        <Content Update="wwwroot\app.css">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
        <Content Update="wwwroot\blazor.web.js">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
    </ItemGroup>


</Project>

