<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <StaticWebAssetBasePath>_content/Modulo2</StaticWebAssetBasePath>
        <RootNamespace>Modulo2</RootNamespace>

    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Horizonte\Horizonte.csproj" />
    </ItemGroup>
    <ItemGroup>
        <None Include="wwwroot\**" CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>
    <ItemGroup>
      <PackageReference Include="Radzen.Blazor" Version="8.4.2" />
    </ItemGroup>
</Project>
