<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <OutputType>Library</OutputType>
        
    </PropertyGroup>



  
    <ItemGroup>
      <ProjectReference Include="..\Horizonte\Horizonte.csproj" />
    </ItemGroup>  
    <ItemGroup>
        <PackageReference Include="Google.Apis.Calendar.v3" Version="1.69.0.3746"   />
        <PackageReference Include="Radzen.Blazor" Version="7.1.5" />
    </ItemGroup>



</Project>
