<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    </PropertyGroup>




    <ItemGroup>
        <SupportedPlatform Include="browser" />
    </ItemGroup>


    <ItemGroup>
      <ProjectReference Include="..\AdminUi.Components\AdminUi.Components.csproj" />
      <ProjectReference Include="..\Horizonte.Extensions.Interactive\Horizonte.Extensions.Interactive.csproj" />
      <ProjectReference Include="..\Horizonte\Horizonte.csproj" />
        
    </ItemGroup>


    <ItemGroup>
      <PackageReference Include="BlazorMonaco" Version="3.4.0" />
    </ItemGroup>

</Project>
